import { extraEntries } from './extraCatalog.js'

function namedProduct(entry, index) {
  const image = entry.image
  const sku = `FAA-N${String(index + 1).padStart(3, '0')}`
  const { top, heart, base } = entry.notes

  return {
    id: `n${index + 1}`,
    name: entry.name,
    category: entry.category,
    size: entry.size || '100ml',
    price: entry.price,
    compareAt: entry.compareAt,
    featured: true,
    image,
    gallery: [image],
    brand: entry.brand,
    concentration: entry.concentration,
    longevity: entry.longevity,
    occasion: entry.occasion,
    family: entry.family,
    sku,
    notes: { top, heart, base },
    description: entry.description,
    details: [
      `SKU ${sku}`,
      `${entry.size || '100ml'} ${entry.concentration} · ${entry.family} family`,
      `Sillage built around ${heart[0].toLowerCase()} and ${base[0].toLowerCase()}`,
      '100% authentic sealed bottle from Faaperfume',
      'Same-day delivery available in Dubai',
      'Returns within 7 days if unopened',
    ],
  }
}

const arrivalEntries = [
  {
    name: 'Armaf Club de Nuit Intense Man',
    image: '/perfumes/bottles/armaf-club-de-nuit-intense-man.jpg',
    brand: 'Armaf',
    category: 'men',
    size: '105ml',
    concentration: 'EDT',
    family: 'Woody Spicy',
    longevity: '8–10 hours',
    occasion: 'Evening',
    price: 109,
    compareAt: 135,
    notes: {
      top: ['Lemon', 'Pineapple', 'Bergamot'],
      heart: ['Birch', 'Jasmine', 'Rose'],
      base: ['Musk', 'Ambergris', 'Patchouli'],
    },
    description:
      'Armaf Club de Nuit Intense Man is a woody-spicy EDP for men. It opens with lemon, pineapple, and bergamot, moves into smoky birch with jasmine and rose, then dries down to musk, ambergris, and patchouli. A bold evening signature with strong projection.',
  },
  {
    name: 'Riiffs Goodness Oud Purple Wave',
    image: '/perfumes/bottles/riiffs-goodness-oud-purple-wave.jpg',
    brand: 'Riiffs',
    category: 'women',
    concentration: 'EDP',
    family: 'Oriental Spicy',
    longevity: '8–10 hours',
    occasion: 'Evening',
    price: 95,
    compareAt: 120,
    notes: {
      top: ['Raspberry', 'Rum'],
      heart: ['Cinnamon', 'Saffron', 'Tobacco'],
      base: ['Cedar', 'Leather', 'Vanilla'],
    },
    description:
      'Riiffs Goodness Oud Purple Wave is an oriental EDP with a rum-and-raspberry opening, a saffron-cinnamon-tobacco heart, and a warm cedar, leather, and vanilla trail. Rich, sweet, and made for night wear.',
  },
  {
    name: 'Ajmal Bastion',
    image: '/perfumes/bottles/ajmal-bastion.jpg',
    brand: 'Ajmal',
    category: 'men',
    concentration: 'EDP',
    family: 'Fresh Woody',
    longevity: '6–8 hours',
    occasion: 'Daytime',
    price: 149,
    compareAt: 195,
    notes: {
      top: ['Pineapple', 'Lemon', 'Mandarin'],
      heart: ['Clary Sage', 'Lavender'],
      base: ['Cedarwood', 'Musk'],
    },
    description:
      'Ajmal Bastion is a fresh woody EDP for men. Pineapple, lemon, and mandarin open the scent, clary sage and lavender sit in the heart, and cedarwood musk keeps it clean through the day.',
  },
  {
    name: 'Oud Arabia Jannat E Zuhur',
    image: '/perfumes/bottles/oud-arabia-jannat-e-zuhur.jpg',
    brand: 'Oud Arabia',
    category: 'unisex',
    concentration: 'Parfum',
    family: 'Floral Oriental',
    longevity: '10+ hours',
    occasion: 'Special occasion',
    price: 265,
    compareAt: 320,
    notes: {
      top: ['Jasmine', 'Taif Rose'],
      heart: ['Lily of the Valley', 'Lavender'],
      base: ['Amber', 'White Musk', 'Bulgarian Rose'],
    },
    description:
      'Oud Arabia Jannat E Zuhur is a unisex floral parfum built around jasmine, Taif rose, and lily of the valley over amber, white musk, and Bulgarian rose. A garden-like trail with exceptional staying power.',
  },
  {
    name: 'Oud Arabia Zainab',
    image: '/perfumes/bottles/oud-arabia-zainab.jpg',
    brand: 'Oud Arabia',
    category: 'unisex',
    concentration: 'Parfum',
    family: 'Oriental Floral',
    longevity: '10+ hours',
    occasion: 'Special occasion',
    price: 265,
    compareAt: 320,
    notes: {
      top: ['Vanilla Oud', 'Blueberry', 'Citrus'],
      heart: ['Rosemary', 'Cashmere Wood'],
      base: ['Agarwood', 'Honey', 'Amber'],
    },
    description:
      'Oud Arabia Zainab is a unisex parfum of vanilla oud, blueberry, and citrus over cashmere woods, then agarwood, honey, and amber. Fresh florals on a lasting musk-and-oud base.',
  },
  {
    name: 'Valentino Born in Roma',
    image: '/perfumes/bottles/valentino-born-in-roma.jpg',
    brand: 'Valentino',
    category: 'men',
    concentration: 'EDT',
    family: 'Woody Aromatic',
    longevity: '6–8 hours',
    occasion: 'All day',
    price: 404,
    compareAt: 520,
    notes: {
      top: ['Violet Leaf', 'Salt'],
      heart: ['Ginger', 'Sage'],
      base: ['Vetiver', 'Woods'],
    },
    description:
      'Valentino Born in Roma is a woody-aromatic EDT for men. Mineral salt and violet leaf open onto ginger and sage, then a vetiver-wood drydown. Modern, urban, and easy to wear all day.',
  },
  {
    name: 'French Avenue Liquid Brun',
    image: '/perfumes/bottles/french-avenue-liquid-brun.jpg',
    brand: 'French Avenue',
    category: 'men',
    concentration: 'EDP',
    family: 'Amber Vanilla',
    longevity: '10+ hours',
    occasion: 'Evening',
    price: 124,
    compareAt: 165,
    notes: {
      top: ['Cinnamon', 'Bergamot', 'Cardamom'],
      heart: ['Bourbon Vanilla', 'Orange Blossom'],
      base: ['Praline', 'Ambroxan', 'Guaiac Wood'],
    },
    description:
      'French Avenue Liquid Brun Eau de Parfum is a spicy amber-vanilla for men. Cinnamon, bergamot, and cardamom lead into bourbon vanilla and orange blossom, then praline, ambroxan, and guaiac wood. A sweet, loud evening scent.',
  },
  {
    name: 'Lattafa Khamrah',
    image: '/perfumes/bottles/lattafa-khamrah.jpg',
    brand: 'Lattafa',
    category: 'unisex',
    concentration: 'EDP',
    family: 'Oriental Gourmand',
    longevity: '10+ hours',
    occasion: 'Evening',
    price: 99,
    compareAt: 199,
    notes: {
      top: ['Cinnamon', 'Nutmeg', 'Bergamot'],
      heart: ['Dates', 'Praline', 'Tuberose'],
      base: ['Vanilla', 'Tonka', 'Amberwood'],
    },
    description:
      'Lattafa Khamrah is a unisex oriental gourmand EDP. Cinnamon and nutmeg open onto dates, praline, and tuberose, then vanilla, tonka, and amberwood. Warm, sweet, and built for cooler evenings.',
  },
  {
    name: 'Lattafa Khamrah Qahwa',
    image: '/perfumes/bottles/lattafa-khamrah-qahwa.jpg',
    brand: 'Lattafa',
    category: 'unisex',
    concentration: 'EDP',
    family: 'Oriental Gourmand',
    longevity: '10+ hours',
    occasion: 'Evening',
    price: 85,
    compareAt: 125,
    notes: {
      top: ['Cinnamon', 'Cardamom', 'Ginger'],
      heart: ['Praline', 'Candied Fruits'],
      base: ['Coffee', 'Vanilla', 'Tonka Bean'],
    },
    description:
      'Lattafa Khamrah Qahwa is the coffee-spiced take on Khamrah. Cinnamon, cardamom, and ginger meet praline and candied fruit, then coffee, vanilla, and tonka. Unisex, sweet, and long-lasting.',
  },
  {
    name: 'Arabiyat Al Noor',
    image: '/perfumes/bottles/arabiyat-al-noor.jpg',
    brand: 'Arabiyat Prestige',
    category: 'unisex',
    concentration: 'EDP',
    family: 'Soft Oriental',
    longevity: '8–10 hours',
    occasion: 'All day',
    price: 155,
    compareAt: 220,
    notes: {
      top: ['Cardamom', 'Saffron', 'Nutmeg'],
      heart: ['Iris', 'Vetiver', 'Fig'],
      base: ['Vanilla', 'Patchouli', 'Leather'],
    },
    description:
      'Arabiyat Prestige Al Noor is a unisex EDP of cardamom, saffron, and nutmeg over iris, vetiver, and fig, finishing on vanilla, patchouli, and leather. Refined enough for day, warm enough for night.',
  },
  {
    name: 'Blue by Ahmed',
    image: '/perfumes/bottles/blue-by-ahmed.jpg',
    brand: 'Ahmed Al Maghribi',
    category: 'men',
    concentration: 'EDP',
    family: 'Aromatic Woody',
    longevity: '8–10 hours',
    occasion: 'Office',
    price: 119,
    compareAt: 199,
    notes: {
      top: ['Grapefruit', 'Lemon', 'Mint'],
      heart: ['Ginger', 'Jasmine', 'Nutmeg'],
      base: ['Cedar', 'Sandalwood', 'Incense'],
    },
    description:
      'Blue by Ahmed from Ahmed Al Maghribi is an aromatic woody EDP for men. Grapefruit, lemon, and mint open the scent, ginger and jasmine sit in the heart, and cedar, sandalwood, and incense close it. Clean, modern, and office-ready.',
  },
  {
    name: "Prada L'Homme Eau de Toilette",
    image: '/perfumes/bottles/prada-lhomme.jpg',
    brand: 'Prada',
    category: 'men',
    concentration: 'EDT',
    family: 'Powdery Woody',
    longevity: '6–8 hours',
    occasion: 'Office',
    price: 455,
    compareAt: 520,
    notes: {
      top: ['Neroli', 'Cardamom', 'Black Pepper'],
      heart: ['Iris', 'Geranium', 'Violet'],
      base: ['Cedar', 'Sandalwood', 'Amber'],
    },
    description:
      "Prada L'Homme Eau de Toilette is a powdery woody scent for men. Neroli and cardamom lead into iris, geranium, and violet, then cedar, sandalwood, and amber. Polished, clean, and made for the office.",
  },
  {
    name: 'Tom Ford Ombré Leather',
    image: '/perfumes/bottles/tom-ford-ombre-leather.jpg',
    brand: 'Tom Ford',
    category: 'men',
    concentration: 'EDP',
    family: 'Leather',
    longevity: '8–10 hours',
    occasion: 'Evening',
    price: 714,
    compareAt: 899,
    notes: {
      top: ['Cardamom'],
      heart: ['Leather', 'Jasmine Sambac'],
      base: ['Patchouli', 'Moss', 'Amber'],
    },
    description:
      'Tom Ford Ombré Leather is a leather EDP for men. Cardamom opens onto smooth leather and jasmine sambac, then patchouli, moss, and amber. A desert-heat leather with presence after dark.',
  },
  {
    name: 'Chopard Oud Malaki Eau de Parfum',
    image: '/perfumes/bottles/chopard-oud-malaki.jpg',
    brand: 'Chopard',
    category: 'men',
    size: '80ml',
    concentration: 'EDP',
    family: 'Woody Oriental',
    longevity: '8–10 hours',
    occasion: 'Evening',
    price: 199,
    compareAt: 350,
    notes: {
      top: ['Grapefruit', 'Lavender'],
      heart: ['Tobacco', 'Leather'],
      base: ['Oud', 'Amber'],
    },
    description:
      'Chopard Oud Malaki Eau de Parfum is a woody oriental for men. Grapefruit and lavender open onto tobacco and leather, then royal oud and amber. Warm, smoky, and built for Gulf evenings.',
  },
  {
    name: 'Afnan 9PM',
    image: '/perfumes/bottles/afnan-9pm.jpg',
    brand: 'Afnan',
    category: 'men',
    concentration: 'EDP',
    family: 'Amber Vanilla',
    longevity: '8–10 hours',
    occasion: 'Evening',
    price: 105,
    compareAt: 120,
    notes: {
      top: ['Apple', 'Cinnamon', 'Bergamot'],
      heart: ['Orange Blossom', 'Lily of the Valley'],
      base: ['Vanilla', 'Tonka', 'Amber'],
    },
    description:
      'Afnan 9PM is an amber-vanilla EDP for men. Apple, cinnamon, and bergamot open onto orange blossom, then vanilla, tonka, and amber. A sweet night-out scent with strong longevity.',
  },
  {
    name: 'Lattafa Eclaire',
    image: '/perfumes/bottles/lattafa-eclaire.jpg',
    brand: 'Lattafa',
    category: 'women',
    concentration: 'EDP',
    family: 'Gourmand',
    longevity: '8–10 hours',
    occasion: 'All day',
    price: 125,
    compareAt: 250,
    notes: {
      top: ['Milk', 'Sugar'],
      heart: ['Honey', 'White Flowers'],
      base: ['Caramel', 'Vanilla', 'Sandalwood'],
    },
    description:
      'Lattafa Eclaire is a gourmand EDP for women. Milk and sugar open onto honey and white flowers, then caramel, vanilla, and sandalwood. Creamy, sweet, and addictive on skin.',
  },
  {
    name: 'Giorgio Armani Stronger With You',
    image: '/perfumes/bottles/armani-stronger-with-you.jpg',
    brand: 'Giorgio Armani',
    category: 'men',
    concentration: 'EDT',
    family: 'Amber Spicy',
    longevity: '6–8 hours',
    occasion: 'Weekend',
    price: 339,
    compareAt: 520,
    notes: {
      top: ['Cardamom', 'Pink Pepper'],
      heart: ['Sage', 'Lavender'],
      base: ['Vanilla', 'Chestnut'],
    },
    description:
      'Giorgio Armani Stronger With You is an amber-spicy EDT for men. Cardamom and pink pepper open onto sage and lavender, then vanilla and chestnut. Warm, slightly sweet, and easy for weekends.',
  },
  {
    name: 'Bleu de Chanel',
    image: '/perfumes/bottles/bleu-de-chanel.jpg',
    brand: 'Chanel',
    category: 'men',
    concentration: 'EDT',
    family: 'Aromatic Woody',
    longevity: '6–8 hours',
    occasion: 'All day',
    price: 549,
    compareAt: 620,
    notes: {
      top: ['Lemon', 'Mint', 'Pink Pepper'],
      heart: ['Ginger', 'Jasmine', 'Nutmeg'],
      base: ['Incense', 'Cedar', 'Sandalwood'],
    },
    description:
      'Bleu de Chanel is an aromatic woody EDT for men. Lemon, mint, and pink pepper open onto ginger and jasmine, then incense, cedar, and sandalwood. A clean classic for any hour.',
  },
  {
    name: 'Elie Saab Le Parfum',
    image: '/perfumes/bottles/elie-saab-le-parfum.jpg',
    brand: 'Elie Saab',
    category: 'women',
    size: '90ml',
    concentration: 'EDP',
    family: 'Floral Oriental',
    longevity: '6–8 hours',
    occasion: 'Special occasion',
    price: 259,
    compareAt: 349,
    notes: {
      top: ['Orange Blossom', 'Jasmine'],
      heart: ['Rose Honey', 'Patchouli'],
      base: ['Cedar', 'Rosewood'],
    },
    description:
      'Elie Saab Le Parfum is a floral oriental EDP for women. Orange blossom and jasmine open onto rose honey and patchouli, then cedar and rosewood. Luminous, elegant, and made for celebrations.',
  },
  {
    name: 'Rasasi Hawas',
    image: '/perfumes/bottles/rasasi-hawas.jpg',
    brand: 'Rasasi',
    category: 'men',
    concentration: 'EDP',
    family: 'Fresh Spicy',
    longevity: '8–10 hours',
    occasion: 'Weekend',
    price: 99,
    compareAt: 175,
    notes: {
      top: ['Apple', 'Bergamot', 'Cinnamon'],
      heart: ['Orange Blossom', 'Cardamom'],
      base: ['Ambergris', 'Musk', 'Driftwood'],
    },
    description:
      'Rasasi Hawas is a fresh spicy EDP for men. Apple, bergamot, and cinnamon open onto orange blossom and cardamom, then ambergris, musk, and driftwood. Aquatic, sweet, and built for heat.',
  },
  {
    name: 'Jean Paul Gaultier Scandal Eau de Parfum',
    image: '/perfumes/bottles/jpg-scandal.jpg',
    brand: 'Jean Paul Gaultier',
    category: 'women',
    size: '80ml',
    concentration: 'EDP',
    family: 'Oriental Floral',
    longevity: '8–10 hours',
    occasion: 'Evening',
    price: 399,
    compareAt: 439,
    notes: {
      top: ['Blood Orange', 'Mandarin'],
      heart: ['Honey', 'Gardenia'],
      base: ['Caramel', 'Patchouli', 'Sandalwood'],
    },
    description:
      'Jean Paul Gaultier Scandal Eau de Parfum is an oriental floral for women. Blood orange and mandarin open onto honey and gardenia, then caramel, patchouli, and sandalwood. Sweet, bold, and unforgettable after dark.',
  },
  {
    name: 'Dior Sauvage Eau de Toilette',
    image: '/perfumes/bottles/dior-sauvage.jpg',
    brand: 'Dior',
    category: 'men',
    concentration: 'EDT',
    family: 'Aromatic Fresh',
    longevity: '6–8 hours',
    occasion: 'All day',
    price: 617,
    compareAt: 750,
    notes: {
      top: ['Calabrian Bergamot', 'Pepper'],
      heart: ['Sichuan Pepper', 'Lavender'],
      base: ['Ambroxan', 'Cedar', 'Labdanum'],
    },
    description:
      'Dior Sauvage Eau de Toilette is an aromatic fresh scent for men. Bergamot and pepper open onto lavender, then ambroxan and cedar. A modern classic for heat and city wear.',
  },
  {
    name: 'Versace Eros Eau de Parfum',
    image: '/perfumes/bottles/versace-eros-edp.jpg',
    brand: 'Versace',
    category: 'men',
    concentration: 'EDP',
    family: 'Fresh Oriental',
    longevity: '8–10 hours',
    occasion: 'Evening',
    price: 299,
    compareAt: 399,
    notes: {
      top: ['Apple', 'Lemon', 'Mint'],
      heart: ['Tonka', 'Ambroxan'],
      base: ['Vanilla', 'Cedar', 'Oakmoss'],
    },
    description:
      'Versace Eros Eau de Parfum is a fresh oriental for men. Apple, lemon, and mint open onto tonka and ambroxan, then vanilla and cedar. Sweet, loud, and built for night.',
  },
  {
    name: 'Paco Rabanne Invictus',
    image: '/perfumes/bottles/invictus.jpg',
    brand: 'Paco Rabanne',
    category: 'men',
    concentration: 'EDT',
    family: 'Fresh Aquatic',
    longevity: '6–8 hours',
    occasion: 'Weekend',
    price: 289,
    compareAt: 399,
    notes: {
      top: ['Grapefruit', 'Marine Accord'],
      heart: ['Bay Leaf', 'Jasmine'],
      base: ['Guaiac Wood', 'Patchouli', 'Oakmoss'],
    },
    description:
      'Paco Rabanne Invictus is a fresh aquatic EDT for men. Grapefruit and marine notes open onto bay leaf and jasmine, then guaiac wood and patchouli. Sporty and easy in the heat.',
  },
  {
    name: 'Lattafa Asad',
    image: '/perfumes/bottles/lattafa-asad.jpg',
    brand: 'Lattafa',
    category: 'men',
    concentration: 'EDP',
    family: 'Oriental Spicy',
    longevity: '8–10 hours',
    occasion: 'Evening',
    price: 88,
    compareAt: 150,
    notes: {
      top: ['Black Pepper', 'Tobacco', 'Pineapple'],
      heart: ['Patchouli', 'Coffee'],
      base: ['Vanilla', 'Amber', 'Benzoin'],
    },
    description:
      'Lattafa Asad is an oriental spicy EDP for men. Black pepper, tobacco, and pineapple open onto patchouli and coffee, then vanilla and amber. Dark, sweet, and long-lasting.',
  },
  {
    name: 'Viktor & Rolf Spicebomb',
    image: '/perfumes/bottles/spicebomb.jpg',
    brand: 'Viktor & Rolf',
    category: 'men',
    size: '90ml',
    concentration: 'EDT',
    family: 'Oriental Spicy',
    longevity: '6–8 hours',
    occasion: 'Evening',
    price: 249,
    compareAt: 399,
    notes: {
      top: ['Bergamot', 'Grapefruit', 'Pink Pepper'],
      heart: ['Cinnamon', 'Saffron'],
      base: ['Tobacco', 'Vetiver', 'Leather'],
    },
    description:
      'Viktor & Rolf Spicebomb is an oriental spicy EDT for men. Citrus and pink pepper open onto cinnamon and saffron, then tobacco, vetiver, and leather. Explosive spice for cooler nights.',
  },
  {
    name: 'Lattafa Yara',
    image: '/perfumes/bottles/lattafa-yara.jpg',
    brand: 'Lattafa',
    category: 'women',
    concentration: 'EDP',
    family: 'Fruity Floral',
    longevity: '6–8 hours',
    occasion: 'All day',
    price: 99,
    compareAt: 150,
    notes: {
      top: ['Heliotrope', 'Orchid', 'Tangerine'],
      heart: ['Gourmand Accord', 'Tropical Fruits'],
      base: ['Vanilla', 'Musk', 'Sandalwood'],
    },
    description:
      'Lattafa Yara is a fruity floral EDP for women. Heliotrope, orchid, and tangerine open onto a gourmand heart, then vanilla, musk, and sandalwood. Soft, sweet, and everyday-ready.',
  },
  {
    name: 'Yves Saint Laurent Libre',
    image: '/perfumes/bottles/ysl-libre.jpg',
    brand: 'Yves Saint Laurent',
    category: 'women',
    size: '90ml',
    concentration: 'EDP',
    family: 'Floral Aromatic',
    longevity: '8–10 hours',
    occasion: 'All day',
    price: 419,
    compareAt: 699,
    notes: {
      top: ['Lavender', 'Mandarin', 'Blackcurrant'],
      heart: ['Orange Blossom', 'Jasmine'],
      base: ['Vanilla', 'Musk', 'Cedar'],
    },
    description:
      'Yves Saint Laurent Libre is a floral aromatic EDP for women. Lavender and mandarin open onto orange blossom and jasmine, then vanilla, musk, and cedar. Bold, luminous, and free.',
  },
  {
    name: 'Gucci Bloom Parfum',
    image: '/perfumes/bottles/gucci-bloom.jpg',
    brand: 'Gucci',
    category: 'women',
    concentration: 'Parfum',
    family: 'White Floral',
    longevity: '8–10 hours',
    occasion: 'Daytime',
    price: 479,
    compareAt: 620,
    notes: {
      top: ['Jasmine', 'Rangoon Creeper'],
      heart: ['Tuberose'],
      base: ['Sandalwood', 'Musk'],
    },
    description:
      'Gucci Bloom Parfum is a white floral for women. Jasmine and Rangoon creeper open onto tuberose, then sandalwood and musk. A garden in full bloom, concentrated.',
  },
  {
    name: 'Mugler Alien',
    image: '/perfumes/bottles/mugler-alien.jpg',
    brand: 'Mugler',
    category: 'women',
    size: '90ml',
    concentration: 'EDP',
    family: 'Woody Floral',
    longevity: '10+ hours',
    occasion: 'Evening',
    price: 335,
    compareAt: 550,
    notes: {
      top: ['Jasmine Sambac'],
      heart: ['Cashmeran'],
      base: ['White Amber'],
    },
    description:
      'Mugler Alien is a woody floral EDP for women. Jasmine sambac sits over cashmeran and white amber. Solar, intense, and famously long on skin.',
  },
  {
    name: 'Lattafa Khamrah Dukhan',
    image: '/perfumes/bottles/khamrah-dukhan.jpg',
    brand: 'Lattafa',
    category: 'unisex',
    concentration: 'EDP',
    family: 'Oriental Smoky',
    longevity: '10+ hours',
    occasion: 'Evening',
    price: 89,
    compareAt: 125,
    notes: {
      top: ['Cinnamon', 'Incense'],
      heart: ['Dates', 'Praline'],
      base: ['Smoke', 'Vanilla', 'Amberwood'],
    },
    description:
      'Lattafa Khamrah Dukhan is the smoky chapter of Khamrah. Cinnamon and incense open onto dates and praline, then smoke, vanilla, and amberwood. Unisex, dark, and winter-ready.',
  },
]

export const namedArrivals = [...arrivalEntries, ...extraEntries].map(namedProduct)

export const products = [...namedArrivals]

export const collections = [
  {
    id: 'best-sellers',
    title: 'Best Sellers',
    to: '/men-perfumes',
    image: '/perfumes/bottles/armaf-club-de-nuit-intense-man.jpg',
  },
  {
    id: 'oud',
    title: 'Oud & Bakhoor',
    to: '/exclusive',
    image: '/perfumes/bottles/oud-arabia-jannat-e-zuhur.jpg',
  },
  {
    id: 'gift-sets',
    title: 'Gift Sets',
    to: '/combos',
    image: '/perfumes/bottles/lattafa-khamrah.jpg',
  },
  {
    id: 'niche',
    title: 'Niche Perfumes',
    to: '/exclusive',
    image: '/perfumes/bottles/arabiyat-al-noor.jpg',
  },
  {
    id: 'men',
    title: 'Men',
    to: '/men-perfumes',
    image: '/perfumes/bottles/dior-sauvage.jpg',
  },
  {
    id: 'women',
    title: 'Women',
    to: '/women-perfumes',
    image: '/perfumes/bottles/lattafa-eclaire.jpg',
  },
]

export const trusts = [
  {
    title: 'Free Shipping',
    text: 'On orders above AED 200',
  },
  {
    title: 'Cash on Delivery',
    text: 'Available on selected items',
  },
  {
    title: 'Authenticity Promise',
    text: '100% genuine bottles only',
  },
  {
    title: 'Easy Returns',
    text: 'Refund within 7 days',
  },
]

export const brandNames = [
  'Armaf',
  'Riiffs',
  'Ajmal',
  'Oud Arabia',
  'Valentino',
  'French Avenue',
  'Lattafa',
  'Arabiyat Prestige',
  'Ahmed Al Maghribi',
  'Prada',
  'Tom Ford',
  'Chopard',
  'Afnan',
  'Giorgio Armani',
  'Chanel',
  'Elie Saab',
  'Rasasi',
  'Jean Paul Gaultier',
  'Dior',
  'Versace',
  'Paco Rabanne',
  'Viktor & Rolf',
  'Yves Saint Laurent',
  'Gucci',
  'Mugler',
  'Calvin Klein',
  'Davidoff',
  'Dunhill',
  'Bentley',
  'Azzaro',
  'Burberry',
  'Hugo Boss',
  'Montblanc',
  'Issey Miyake',
  'Carolina Herrera',
  'Coach',
  'Narciso Rodriguez',
  'Dolce & Gabbana',
  'Givenchy',
  'Jimmy Choo',
  'Mancera',
  'Byredo',
  'Jo Malone',
  'Maison Margiela',
  'Guerlain',
  'Hermès',
  'Maison Alhambra',
  'Al Haramain',
  'Estée Lauder',
]

export const combos = [
  {
    id: 'c1',
    name: 'His & Hers Duo',
    category: 'combo',
    size: '2 bottles',
    includes: ['Rasasi Hawas', 'Lattafa Eclaire'],
    price: 189,
    compareAt: 224,
    featured: true,
    badge: 'Save 16%',
    image: '/perfumes/bottles/rasasi-hawas.jpg',
    gallery: ['/perfumes/bottles/rasasi-hawas.jpg'],
    description:
      'Hawas for him and Eclaire for her — two full-size bestsellers in one gift-ready pair.',
    details: [
      'Rasasi Hawas 100ml + Lattafa Eclaire 100ml',
      'Better value than buying separately',
      'Ideal anniversary or couple gift',
      'Authentic Faaperfume sourcing',
    ],
  },
  {
    id: 'c2',
    name: 'Oud Ritual Trio',
    category: 'combo',
    size: '3 bottles',
    includes: ['Oud Arabia Jannat E Zuhur', 'Oud Arabia Zainab', 'Arabiyat Al Noor'],
    price: 599,
    compareAt: 685,
    featured: true,
    badge: 'Best value',
    image: '/perfumes/bottles/oud-arabia-jannat-e-zuhur.jpg',
    gallery: ['/perfumes/bottles/oud-arabia-jannat-e-zuhur.jpg'],
    description:
      'Three oud-laced signatures for layering through the evening — florals, musk, and spice.',
    details: [
      'Jannat E Zuhur + Zainab + Al Noor',
      'Built for Gulf evenings',
      'Layer together or wear alone',
      'Priced below buying separately',
    ],
  },
  {
    id: 'c3',
    name: 'Arabian Bestsellers',
    category: 'combo',
    size: '3 × 100ml',
    includes: ['Lattafa Khamrah', 'Afnan 9PM', 'Lattafa Asad'],
    price: 249,
    compareAt: 292,
    featured: true,
    badge: 'New',
    image: '/perfumes/bottles/lattafa-khamrah.jpg',
    gallery: ['/perfumes/bottles/lattafa-khamrah.jpg'],
    description:
      'Three Gulf crowd-pleasers — Khamrah, 9PM, and Asad — for discovering your next signature.',
    details: [
      'Three sealed 100ml bottles',
      'Sweet, spicy, and night-out profiles',
      'Strong longevity in the heat',
      'Authentic sealed stock',
    ],
  },
  {
    id: 'c4',
    name: 'Evening Layering Pair',
    category: 'combo',
    size: '2 × 100ml',
    includes: ['French Avenue Liquid Brun', 'Lattafa Khamrah Qahwa'],
    price: 179,
    compareAt: 209,
    featured: true,
    badge: 'Limited',
    image: '/perfumes/bottles/french-avenue-liquid-brun.jpg',
    gallery: ['/perfumes/bottles/french-avenue-liquid-brun.jpg'],
    description:
      'Vanilla-praline Liquid Brun over coffee-spiced Qahwa — a night-out layering duo.',
    details: [
      'Liquid Brun 100ml + Khamrah Qahwa 100ml',
      'Designed to layer',
      'Sweet gourmand pairing',
      'Gift-ready',
    ],
  },
  {
    id: 'c5',
    name: 'Fresh Day Combo',
    category: 'combo',
    size: '2 bottles',
    includes: ['Blue by Ahmed', 'Armaf Club de Nuit Intense Man'],
    price: 199,
    compareAt: 228,
    featured: false,
    badge: 'Summer edit',
    image: '/perfumes/bottles/blue-by-ahmed.jpg',
    gallery: ['/perfumes/bottles/blue-by-ahmed.jpg'],
    description:
      'Citrus-woody Blue by Ahmed with smoky-fruity Club de Nuit Intense Man — a day-to-night rotation.',
    details: [
      'Blue by Ahmed 100ml + CDNIM 105ml',
      'Light enough for office, strong enough for evening',
      'Summer seasonal offer',
      'Authentic sealed stock',
    ],
  },
  {
    id: 'c6',
    name: 'Gift Ready Couples Set',
    category: 'combo',
    size: 'Gift box',
    includes: ['Valentino Born in Roma', 'Elie Saab Le Parfum'],
    price: 579,
    compareAt: 663,
    featured: true,
    badge: 'Gift set',
    image: '/perfumes/bottles/valentino-born-in-roma.jpg',
    gallery: ['/perfumes/bottles/valentino-born-in-roma.jpg'],
    description:
      'Designer pair for gifting — Valentino Born in Roma for him and Elie Saab Le Parfum for her.',
    details: [
      'Valentino Born in Roma 100ml + Elie Saab Le Parfum 90ml',
      'Two full-size designer bottles',
      'Ribbon-ready presentation',
      'Perfect for celebrations',
    ],
  },
  {
    id: 'c7',
    name: 'Cool Water Couple',
    category: 'combo',
    size: '2 × 100ml',
    includes: [
      'Davidoff Cool Water Parfum for Men 100ML',
      'Davidoff Cool Water EDT for Women 100ML',
    ],
    price: 189,
    compareAt: 224,
    featured: true,
    badge: 'His & hers',
    image: '/perfumes/bottles/davidoff-cool-water-parfum-for-men-100ml.jpg',
    gallery: ['/perfumes/bottles/davidoff-cool-water-parfum-for-men-100ml.jpg'],
    description:
      'Davidoff Cool Water for him and her — a fresh aquatic pair at a bundle price.',
    details: [
      'Cool Water Parfum 100ml + Cool Water Woman 100ml',
      'Classic aquatic signatures',
      'Better value than buying separately',
      'Authentic sealed stock',
    ],
  },
  {
    id: 'c8',
    name: 'CK Shock Duo',
    category: 'combo',
    size: '2 × 100ml',
    includes: [
      'Calvin Klein One Shock for Him EDT for Men 100ML',
      'Calvin Klein One Shock for Her EDT For Women 100ML',
    ],
    price: 129,
    compareAt: 150,
    featured: true,
    badge: 'Save 14%',
    image: '/perfumes/bottles/calvin-klein-one-shock-for-him-edt-for-men-100ml.jpg',
    gallery: ['/perfumes/bottles/calvin-klein-one-shock-for-him-edt-for-men-100ml.jpg'],
    description: 'Calvin Klein One Shock his and hers — a matching everyday pair.',
    details: [
      'One Shock Him 100ml + One Shock Her 100ml',
      'Office and weekend friendly',
      'Gift-ready duo',
      'Authentic sealed stock',
    ],
  },
  {
    id: 'c9',
    name: 'Burberry London Pair',
    category: 'combo',
    size: '2 × 100ml',
    includes: [
      'Burberry London EDT for Men 100ML',
      'Burberry London EDP for Women 100ML',
    ],
    price: 219,
    compareAt: 257,
    featured: true,
    badge: 'Designer duo',
    image: '/perfumes/bottles/burberry-london-edt-for-men-100ml.jpg',
    gallery: ['/perfumes/bottles/burberry-london-edt-for-men-100ml.jpg'],
    description: 'Burberry London for him and her — British classics in one set.',
    details: [
      'London Man EDT 100ml + London Woman EDP 100ml',
      'Two full-size Burberry bottles',
      'Priced below buying separately',
      'Authentic Faaperfume sourcing',
    ],
  },
  {
    id: 'c10',
    name: 'Oud Prestige Trio',
    category: 'combo',
    size: '3 bottles',
    includes: [
      'Lattafa Badee Al Oud For Glory For Unisex Eau de Parfum 100ML',
      "Lattafa Bade'E Al Oud Amethyst For Unisex Eau De Parfum 100ML",
      'Al Haramain Detour Noir For Unisex Eau De Parfume 100ML',
    ],
    price: 199,
    compareAt: 239,
    featured: true,
    badge: 'Exclusive',
    image: '/perfumes/bottles/lattafa-badee-al-oud-for-glory-for-unisex-eau-de-parfum-100ml.jpg',
    gallery: ['/perfumes/bottles/lattafa-badee-al-oud-for-glory-for-unisex-eau-de-parfum-100ml.jpg'],
    description:
      'Three unisex oud signatures — For Glory, Amethyst, and Detour Noir — for layering or gifting.',
    details: [
      'Three complementary oud profiles',
      'Built for Gulf evenings',
      'Layer together or wear alone',
      'Priced below buying separately',
    ],
  },
  {
    id: 'c11',
    name: 'Mancera Night Pair',
    category: 'combo',
    size: '2 bottles',
    includes: [
      'Mancera Cedrat Boise Eau De Parfum for Unisex',
      'Mancera Red Tobacco EDP for Unisex 120ML',
    ],
    price: 569,
    compareAt: 658,
    featured: true,
    badge: 'Niche',
    image: '/perfumes/bottles/mancera-red-tobacco-edp-for-unisex-120ml.jpg',
    gallery: ['/perfumes/bottles/mancera-red-tobacco-edp-for-unisex-120ml.jpg'],
    description:
      'Cedrat Boise and Red Tobacco — two Mancera powerhouses at a set price.',
    details: [
      'Cedrat Boise + Red Tobacco 120ml',
      'Niche-strength projection',
      'Better value than singles',
      'Authentic sealed stock',
    ],
  },
  {
    id: 'c12',
    name: 'Floral Evening Duo',
    category: 'combo',
    size: '2 bottles',
    includes: [
      'Elie Saab Girl Of Now Eau De Parfum for Women',
      'Gucci Bamboo Eau De Parfum for Women',
    ],
    price: 399,
    compareAt: 475,
    featured: true,
    badge: 'For her',
    image: '/perfumes/bottles/elie-saab-girl-of-now-eau-de-parfum-for-women.jpg',
    gallery: ['/perfumes/bottles/elie-saab-girl-of-now-eau-de-parfum-for-women.jpg'],
    description:
      'Girl of Now and Gucci Bamboo — two luminous florals for gifting or rotation.',
    details: [
      'Elie Saab Girl of Now + Gucci Bamboo',
      'Two full-size women’s EDPs',
      'Celebration-ready pairing',
      'Authentic Faaperfume sourcing',
    ],
  },
]

export const heroImages = {
  home: '/perfumes/bottles/lattafa-khamrah.jpg',
  men: '/perfumes/bottles/dior-sauvage.jpg',
  women: '/perfumes/bottles/elie-saab-le-parfum.jpg',
  exclusive: '/perfumes/bottles/oud-arabia-zainab.jpg',
  story: '/perfumes/bottles/french-avenue-liquid-brun.jpg',
  combos: '/perfumes/bottles/valentino-born-in-roma.jpg',
}

export function getProductsByCategory(category) {
  return products.filter((p) => p.category === category)
}

export function getFeaturedProducts() {
  return products.filter((p) => p.featured)
}

export function getFeaturedCombos() {
  return combos.filter((c) => c.featured)
}

export function findCatalogItem(id) {
  return products.find((p) => p.id === id) || combos.find((c) => c.id === id) || null
}

export function formatProductNote(product) {
  if (product.category === 'combo') {
    return `Combo · ${product.size}`
  }
  const label =
    product.category === 'men'
      ? 'Men'
      : product.category === 'women'
        ? 'Women'
        : 'Unisex'
  return `${label} · ${product.size}`
}
