export const extraEntries = [
  {
    name: "Calvin Klein One Shock for Him EDT for Men 100ML",
    image: "/perfumes/bottles/calvin-klein-one-shock-for-him-edt-for-men-100ml.jpg",
    brand: "Calvin Klein",
    category: "men",
    size: "100ml",
    concentration: "EDT",
    family: "Woody Spicy",
    longevity: "6–8 hours",
    occasion: "All day",
    price: 75,
    compareAt: 159,
    notes: {
      top: ["Bergamot", "Lemon"],
      heart: ["Cedar", "Nutmeg"],
      base: ["Amber", "Musk"],
    },
    description: "Calvin Klein One Shock for Him EDT for Men 100ML by Calvin Klein is a woody spicy EDT for men. Opening with bergamot and lemon, it settles into cedar and nutmeg before a lasting trail of amber and musk.",
  },
  {
    name: "Davidoff Adventure EDT for Men 100ML",
    image: "/perfumes/bottles/davidoff-adventure-edt-for-men-100ml.jpg",
    brand: "Davidoff",
    category: "men",
    size: "100ml",
    concentration: "EDT",
    family: "Woody Spicy",
    longevity: "6–8 hours",
    occasion: "All day",
    price: 74,
    compareAt: 198,
    notes: {
      top: ["Pineapple", "Mint"],
      heart: ["Jasmine", "Iris"],
      base: ["Tonka", "Vanilla"],
    },
    description: "Davidoff Adventure EDT for Men 100ML by Davidoff is a woody spicy EDT for men. Opening with pineapple and mint, it settles into jasmine and iris before a lasting trail of tonka and vanilla.",
  },
  {
    name: "Calvin Klein IN2U EDT for Men 100ML",
    image: "/perfumes/bottles/calvin-klein-in2u-edt-for-men-100ml.jpg",
    brand: "Calvin Klein",
    category: "men",
    size: "100ml",
    concentration: "EDT",
    family: "Woody Spicy",
    longevity: "6–8 hours",
    occasion: "All day",
    price: 71,
    compareAt: 159,
    notes: {
      top: ["Grapefruit", "Cardamom"],
      heart: ["Cedar", "Nutmeg"],
      base: ["Amber", "Musk"],
    },
    description: "Calvin Klein IN2U EDT for Men 100ML by Calvin Klein is a woody spicy EDT for men. Opening with grapefruit and cardamom, it settles into cedar and nutmeg before a lasting trail of amber and musk.",
  },
  {
    name: "Dunhill Desire Blue EDT for Men 100ML",
    image: "/perfumes/bottles/dunhill-desire-blue-edt-for-men-100ml.jpg",
    brand: "Dunhill",
    category: "men",
    size: "100ml",
    concentration: "EDT",
    family: "Aromatic Fresh",
    longevity: "6–8 hours",
    occasion: "All day",
    price: 94,
    compareAt: 169,
    notes: {
      top: ["Apple", "Pink Pepper"],
      heart: ["Lavender", "Geranium"],
      base: ["Tonka", "Vanilla"],
    },
    description: "Dunhill Desire Blue EDT for Men 100ML by Dunhill is a aromatic fresh EDT for men. Opening with apple and pink pepper, it settles into lavender and geranium before a lasting trail of tonka and vanilla.",
  },
  {
    name: "Dunhill Desire Black Eau De Toilette for Men",
    image: "/perfumes/bottles/dunhill-desire-black-eau-de-toilette-for-men.jpg",
    brand: "Dunhill",
    category: "men",
    size: "100ml",
    concentration: "EDT",
    family: "Woody Spicy",
    longevity: "6–8 hours",
    occasion: "All day",
    price: 99,
    compareAt: 149,
    notes: {
      top: ["Pineapple", "Mint"],
      heart: ["Jasmine", "Iris"],
      base: ["Sandalwood", "Vetiver"],
    },
    description: "Dunhill Desire Black Eau De Toilette for Men by Dunhill is a woody spicy EDT for men. Opening with pineapple and mint, it settles into jasmine and iris before a lasting trail of sandalwood and vetiver.",
  },
  {
    name: "Bentley For Men EDT for Men 100ML",
    image: "/perfumes/bottles/bentley-for-men-edt-for-men-100ml.jpg",
    brand: "Bentley",
    category: "men",
    size: "100ml",
    concentration: "EDT",
    family: "Woody Spicy",
    longevity: "6–8 hours",
    occasion: "All day",
    price: 84,
    compareAt: 199,
    notes: {
      top: ["Bergamot", "Lemon"],
      heart: ["Jasmine", "Iris"],
      base: ["Sandalwood", "Vetiver"],
    },
    description: "Bentley For Men EDT for Men 100ML by Bentley is a woody spicy EDT for men. Opening with bergamot and lemon, it settles into jasmine and iris before a lasting trail of sandalwood and vetiver.",
  },
  {
    name: "Afnan Perfumes Supremacy EDP For Men 100ml",
    image: "/perfumes/bottles/afnan-perfumes-supremacy-edp-for-men-100ml.jpg",
    brand: "Afnan",
    category: "men",
    size: "100ml",
    concentration: "EDP",
    family: "Woody Spicy",
    longevity: "8–10 hours",
    occasion: "All day",
    price: 109,
    compareAt: 179,
    notes: {
      top: ["Apple", "Pink Pepper"],
      heart: ["Jasmine", "Iris"],
      base: ["Sandalwood", "Vetiver"],
    },
    description: "Afnan Perfumes Supremacy EDP For Men 100ml by Afnan is a woody spicy EDP for men. Opening with apple and pink pepper, it settles into jasmine and iris before a lasting trail of sandalwood and vetiver.",
  },
  {
    name: "Azzaro Sport EDT for Men 100ML",
    image: "/perfumes/bottles/azzaro-sport-edt-for-men-100ml.jpg",
    brand: "Azzaro",
    category: "men",
    size: "100ml",
    concentration: "EDT",
    family: "Woody Spicy",
    longevity: "6–8 hours",
    occasion: "All day",
    price: 109,
    compareAt: 199,
    notes: {
      top: ["Grapefruit", "Cardamom"],
      heart: ["Lavender", "Geranium"],
      base: ["Sandalwood", "Vetiver"],
    },
    description: "Azzaro Sport EDT for Men 100ML by Azzaro is a woody spicy EDT for men. Opening with grapefruit and cardamom, it settles into lavender and geranium before a lasting trail of sandalwood and vetiver.",
  },
  {
    name: "Davidoff The Game Eau De Toilette for Men",
    image: "/perfumes/bottles/davidoff-the-game-eau-de-toilette-for-men.jpg",
    brand: "Davidoff",
    category: "men",
    size: "100ml",
    concentration: "EDT",
    family: "Woody Spicy",
    longevity: "6–8 hours",
    occasion: "All day",
    price: 75,
    compareAt: 109,
    notes: {
      top: ["Apple", "Pink Pepper"],
      heart: ["Lavender", "Geranium"],
      base: ["Sandalwood", "Vetiver"],
    },
    description: "Davidoff The Game Eau De Toilette for Men by Davidoff is a woody spicy EDT for men. Opening with apple and pink pepper, it settles into lavender and geranium before a lasting trail of sandalwood and vetiver.",
  },
  {
    name: "Davidoff Champion EDT for Men 90ML",
    image: "/perfumes/bottles/davidoff-champion-edt-for-men-90ml.jpg",
    brand: "Davidoff",
    category: "men",
    size: "90ml",
    concentration: "EDT",
    family: "Woody Spicy",
    longevity: "6–8 hours",
    occasion: "All day",
    price: 77,
    compareAt: 149,
    notes: {
      top: ["Bergamot", "Lemon"],
      heart: ["Lavender", "Geranium"],
      base: ["Sandalwood", "Vetiver"],
    },
    description: "Davidoff Champion EDT for Men 90ML by Davidoff is a woody spicy EDT for men. Opening with bergamot and lemon, it settles into lavender and geranium before a lasting trail of sandalwood and vetiver.",
  },
  {
    name: "Hugo Boss Man Eau De Toilette",
    image: "/perfumes/bottles/hugo-boss-man-eau-de-toilette.jpg",
    brand: "Hugo Boss",
    category: "men",
    size: "100ml",
    concentration: "EDT",
    family: "Woody Spicy",
    longevity: "6–8 hours",
    occasion: "All day",
    price: 104,
    compareAt: 279,
    notes: {
      top: ["Pineapple", "Mint"],
      heart: ["Sage", "Cinnamon"],
      base: ["Tonka", "Vanilla"],
    },
    description: "Hugo Boss Man Eau De Toilette by Hugo Boss is a woody spicy EDT for men. Opening with pineapple and mint, it settles into sage and cinnamon before a lasting trail of tonka and vanilla.",
  },
  {
    name: "Calvin Klein Eternity Aqua EDT for Men 100ML",
    image: "/perfumes/bottles/calvin-klein-eternity-aqua-edt-for-men-100ml.jpg",
    brand: "Calvin Klein",
    category: "men",
    size: "100ml",
    concentration: "EDT",
    family: "Woody Spicy",
    longevity: "6–8 hours",
    occasion: "All day",
    price: 89,
    compareAt: 199,
    notes: {
      top: ["Pineapple", "Mint"],
      heart: ["Jasmine", "Iris"],
      base: ["Amber", "Musk"],
    },
    description: "Calvin Klein Eternity Aqua EDT for Men 100ML by Calvin Klein is a woody spicy EDT for men. Opening with pineapple and mint, it settles into jasmine and iris before a lasting trail of amber and musk.",
  },
  {
    name: "Hugo Boss In Motion Men EDT 100ML",
    image: "/perfumes/bottles/hugo-boss-in-motion-men-edt-100ml.jpg",
    brand: "Hugo Boss",
    category: "men",
    size: "100ml",
    concentration: "EDT",
    family: "Woody Spicy",
    longevity: "6–8 hours",
    occasion: "All day",
    price: 109,
    compareAt: 149,
    notes: {
      top: ["Bergamot", "Lemon"],
      heart: ["Lavender", "Geranium"],
      base: ["Sandalwood", "Vetiver"],
    },
    description: "Hugo Boss In Motion Men EDT 100ML by Hugo Boss is a woody spicy EDT for men. Opening with bergamot and lemon, it settles into lavender and geranium before a lasting trail of sandalwood and vetiver.",
  },
  {
    name: "Dunhill Edition Eau De Toilette for Men",
    image: "/perfumes/bottles/dunhill-edition-eau-de-toilette-for-men.jpg",
    brand: "Dunhill",
    category: "men",
    size: "100ml",
    concentration: "EDT",
    family: "Woody Spicy",
    longevity: "6–8 hours",
    occasion: "All day",
    price: 109,
    compareAt: 149,
    notes: {
      top: ["Apple", "Pink Pepper"],
      heart: ["Sage", "Cinnamon"],
      base: ["Amber", "Musk"],
    },
    description: "Dunhill Edition Eau De Toilette for Men by Dunhill is a woody spicy EDT for men. Opening with apple and pink pepper, it settles into sage and cinnamon before a lasting trail of amber and musk.",
  },
  {
    name: "Dunhill Desire Silver Eau De Toilette for Men",
    image: "/perfumes/bottles/dunhill-desire-silver-eau-de-toilette-for-men.jpg",
    brand: "Dunhill",
    category: "men",
    size: "100ml",
    concentration: "EDT",
    family: "Woody Spicy",
    longevity: "6–8 hours",
    occasion: "All day",
    price: 109,
    compareAt: 149,
    notes: {
      top: ["Grapefruit", "Cardamom"],
      heart: ["Lavender", "Geranium"],
      base: ["Amber", "Musk"],
    },
    description: "Dunhill Desire Silver Eau De Toilette for Men by Dunhill is a woody spicy EDT for men. Opening with grapefruit and cardamom, it settles into lavender and geranium before a lasting trail of amber and musk.",
  },
  {
    name: "Azzaro Aqua Frost Eau De Toilette for Men",
    image: "/perfumes/bottles/azzaro-aqua-frost-eau-de-toilette-for-men.jpg",
    brand: "Azzaro",
    category: "men",
    size: "100ml",
    concentration: "EDT",
    family: "Woody Spicy",
    longevity: "6–8 hours",
    occasion: "All day",
    price: 109,
    compareAt: 199,
    notes: {
      top: ["Pineapple", "Mint"],
      heart: ["Jasmine", "Iris"],
      base: ["Tonka", "Vanilla"],
    },
    description: "Azzaro Aqua Frost Eau De Toilette for Men by Azzaro is a woody spicy EDT for men. Opening with pineapple and mint, it settles into jasmine and iris before a lasting trail of tonka and vanilla.",
  },
  {
    name: "Bentley For Men Azure EDT for Men 100ML",
    image: "/perfumes/bottles/bentley-for-men-azure-edt-for-men-100ml.jpg",
    brand: "Bentley",
    category: "men",
    size: "100ml",
    concentration: "EDT",
    family: "Woody Spicy",
    longevity: "6–8 hours",
    occasion: "All day",
    price: 109,
    compareAt: 199,
    notes: {
      top: ["Apple", "Pink Pepper"],
      heart: ["Lavender", "Geranium"],
      base: ["Tonka", "Vanilla"],
    },
    description: "Bentley For Men Azure EDT for Men 100ML by Bentley is a woody spicy EDT for men. Opening with apple and pink pepper, it settles into lavender and geranium before a lasting trail of tonka and vanilla.",
  },
  {
    name: "Azzaro Pour Homme EDT for Men 100ML",
    image: "/perfumes/bottles/azzaro-pour-homme-edt-for-men-100ml.jpg",
    brand: "Azzaro",
    category: "men",
    size: "100ml",
    concentration: "EDT",
    family: "Woody Spicy",
    longevity: "6–8 hours",
    occasion: "All day",
    price: 109,
    compareAt: 199,
    notes: {
      top: ["Bergamot", "Lemon"],
      heart: ["Cedar", "Nutmeg"],
      base: ["Oud", "Leather"],
    },
    description: "Azzaro Pour Homme EDT for Men 100ML by Azzaro is a woody spicy EDT for men. Opening with bergamot and lemon, it settles into cedar and nutmeg before a lasting trail of oud and leather.",
  },
  {
    name: "Burberry EDT for Men 100ML",
    image: "/perfumes/bottles/burberry-edt-for-men-100ml.jpg",
    brand: "Burberry",
    category: "men",
    size: "100ml",
    concentration: "EDT",
    family: "Woody Spicy",
    longevity: "6–8 hours",
    occasion: "All day",
    price: 118,
    compareAt: 280,
    notes: {
      top: ["Grapefruit", "Cardamom"],
      heart: ["Lavender", "Geranium"],
      base: ["Oud", "Leather"],
    },
    description: "Burberry EDT for Men 100ML by Burberry is a woody spicy EDT for men. Opening with grapefruit and cardamom, it settles into lavender and geranium before a lasting trail of oud and leather.",
  },
  {
    name: "Burberry London EDT for Men 100ML",
    image: "/perfumes/bottles/burberry-london-edt-for-men-100ml.jpg",
    brand: "Burberry",
    category: "men",
    size: "100ml",
    concentration: "EDT",
    family: "Woody Spicy",
    longevity: "6–8 hours",
    occasion: "All day",
    price: 118,
    compareAt: 199,
    notes: {
      top: ["Grapefruit", "Cardamom"],
      heart: ["Cedar", "Nutmeg"],
      base: ["Amber", "Musk"],
    },
    description: "Burberry London EDT for Men 100ML by Burberry is a woody spicy EDT for men. Opening with grapefruit and cardamom, it settles into cedar and nutmeg before a lasting trail of amber and musk.",
  },
  {
    name: "Estee Lauder Pleasures Cologne EDT for Men 100ML",
    image: "/perfumes/bottles/estee-lauder-pleasures-cologne-edt-for-men-100ml.jpg",
    brand: "Estee Lauder",
    category: "men",
    size: "100ml",
    concentration: "EDT",
    family: "Woody Spicy",
    longevity: "6–8 hours",
    occasion: "All day",
    price: 119,
    compareAt: 299,
    notes: {
      top: ["Bergamot", "Lemon"],
      heart: ["Jasmine", "Iris"],
      base: ["Tonka", "Vanilla"],
    },
    description: "Estee Lauder Pleasures Cologne EDT for Men 100ML by Estee Lauder is a woody spicy EDT for men. Opening with bergamot and lemon, it settles into jasmine and iris before a lasting trail of tonka and vanilla.",
  },
  {
    name: "Burberry Weekend EDT for Men 100ML",
    image: "/perfumes/bottles/burberry-weekend-edt-for-men-100ml.jpg",
    brand: "Burberry",
    category: "men",
    size: "100ml",
    concentration: "EDT",
    family: "Woody Spicy",
    longevity: "6–8 hours",
    occasion: "All day",
    price: 119,
    compareAt: 199,
    notes: {
      top: ["Grapefruit", "Cardamom"],
      heart: ["Lavender", "Geranium"],
      base: ["Sandalwood", "Vetiver"],
    },
    description: "Burberry Weekend EDT for Men 100ML by Burberry is a woody spicy EDT for men. Opening with grapefruit and cardamom, it settles into lavender and geranium before a lasting trail of sandalwood and vetiver.",
  },
  {
    name: "Issey Miyake L`Eau D`Issey Sport For Men EDT 100ML",
    image: "/perfumes/bottles/issey-miyake-l-eau-d-issey-sport-for-men-edt-100ml.jpg",
    brand: "Issey Miyake",
    category: "men",
    size: "100ml",
    concentration: "EDT",
    family: "Woody Spicy",
    longevity: "6–8 hours",
    occasion: "All day",
    price: 113,
    compareAt: 362,
    notes: {
      top: ["Apple", "Pink Pepper"],
      heart: ["Lavender", "Geranium"],
      base: ["Amber", "Musk"],
    },
    description: "Issey Miyake L`Eau D`Issey Sport For Men EDT 100ML by Issey Miyake is a woody spicy EDT for men. Opening with apple and pink pepper, it settles into lavender and geranium before a lasting trail of amber and musk.",
  },
  {
    name: "Bentley Infinite EDT for Men 100ML",
    image: "/perfumes/bottles/bentley-infinite-edt-for-men-100ml.jpg",
    brand: "Bentley",
    category: "men",
    size: "100ml",
    concentration: "EDT",
    family: "Woody Spicy",
    longevity: "6–8 hours",
    occasion: "All day",
    price: 119,
    compareAt: 199,
    notes: {
      top: ["Pineapple", "Mint"],
      heart: ["Jasmine", "Iris"],
      base: ["Oud", "Leather"],
    },
    description: "Bentley Infinite EDT for Men 100ML by Bentley is a woody spicy EDT for men. Opening with pineapple and mint, it settles into jasmine and iris before a lasting trail of oud and leather.",
  },
  {
    name: "Montblanc Legend Red Eau De Parfum for Men",
    image: "/perfumes/bottles/montblanc-legend-red-eau-de-parfum-for-men.jpg",
    brand: "Montblanc",
    category: "men",
    size: "100ml",
    concentration: "EDP",
    family: "Woody Spicy",
    longevity: "8–10 hours",
    occasion: "All day",
    price: 127,
    compareAt: 209,
    notes: {
      top: ["Apple", "Pink Pepper"],
      heart: ["Sage", "Cinnamon"],
      base: ["Oud", "Leather"],
    },
    description: "Montblanc Legend Red Eau De Parfum for Men by Montblanc is a woody spicy EDP for men. Opening with apple and pink pepper, it settles into sage and cinnamon before a lasting trail of oud and leather.",
  },
  {
    name: "Rasasi Shuhrah EDP for Men 100ML",
    image: "/perfumes/bottles/rasasi-shuhrah-edp-for-men-100ml.jpg",
    brand: "Rasasi",
    category: "men",
    size: "100ml",
    concentration: "EDP",
    family: "Woody Spicy",
    longevity: "8–10 hours",
    occasion: "All day",
    price: 125,
    compareAt: 199,
    notes: {
      top: ["Apple", "Pink Pepper"],
      heart: ["Cedar", "Nutmeg"],
      base: ["Tonka", "Vanilla"],
    },
    description: "Rasasi Shuhrah EDP for Men 100ML by Rasasi is a woody spicy EDP for men. Opening with apple and pink pepper, it settles into cedar and nutmeg before a lasting trail of tonka and vanilla.",
  },
  {
    name: "Burberry Touch EDT for Men 100ML",
    image: "/perfumes/bottles/burberry-touch-edt-for-men-100ml.jpg",
    brand: "Burberry",
    category: "men",
    size: "100ml",
    concentration: "EDT",
    family: "Woody Spicy",
    longevity: "6–8 hours",
    occasion: "All day",
    price: 139,
    compareAt: 199,
    notes: {
      top: ["Apple", "Pink Pepper"],
      heart: ["Lavender", "Geranium"],
      base: ["Oud", "Leather"],
    },
    description: "Burberry Touch EDT for Men 100ML by Burberry is a woody spicy EDT for men. Opening with apple and pink pepper, it settles into lavender and geranium before a lasting trail of oud and leather.",
  },
  {
    name: "Versace L`Homme Eau De Toilette For Men",
    image: "/perfumes/bottles/versace-l-homme-eau-de-toilette-for-men.jpg",
    brand: "Versace",
    category: "men",
    size: "100ml",
    concentration: "EDT",
    family: "Woody Spicy",
    longevity: "6–8 hours",
    occasion: "All day",
    price: 139,
    compareAt: 249,
    notes: {
      top: ["Bergamot", "Lemon"],
      heart: ["Lavender", "Geranium"],
      base: ["Sandalwood", "Vetiver"],
    },
    description: "Versace L`Homme Eau De Toilette For Men by Versace is a woody spicy EDT for men. Opening with bergamot and lemon, it settles into lavender and geranium before a lasting trail of sandalwood and vetiver.",
  },
  {
    name: "Versace The Dreamer Eau De Toilette for Men",
    image: "/perfumes/bottles/versace-the-dreamer-eau-de-toilette-for-men.jpg",
    brand: "Versace",
    category: "men",
    size: "100ml",
    concentration: "EDT",
    family: "Woody Spicy",
    longevity: "6–8 hours",
    occasion: "All day",
    price: 139,
    compareAt: 199,
    notes: {
      top: ["Apple", "Pink Pepper"],
      heart: ["Lavender", "Geranium"],
      base: ["Tonka", "Vanilla"],
    },
    description: "Versace The Dreamer Eau De Toilette for Men by Versace is a woody spicy EDT for men. Opening with apple and pink pepper, it settles into lavender and geranium before a lasting trail of tonka and vanilla.",
  },
  {
    name: "Davidoff Cool Water Parfum for Men 100ML",
    image: "/perfumes/bottles/davidoff-cool-water-parfum-for-men-100ml.jpg",
    brand: "Davidoff",
    category: "men",
    size: "100ml",
    concentration: "Parfum",
    family: "Woody Spicy",
    longevity: "8–10 hours",
    occasion: "All day",
    price: 144,
    compareAt: 209,
    notes: {
      top: ["Bergamot", "Lemon"],
      heart: ["Cedar", "Nutmeg"],
      base: ["Oud", "Leather"],
    },
    description: "Davidoff Cool Water Parfum for Men 100ML by Davidoff is a woody spicy Parfum for men. Opening with bergamot and lemon, it settles into cedar and nutmeg before a lasting trail of oud and leather.",
  },
  {
    name: "Carolina Herrera CH Men EDT For Men 100ML",
    image: "/perfumes/bottles/carolina-herrera-ch-men-edt-for-men-100ml.jpg",
    brand: "Carolina Herrera",
    category: "men",
    size: "100ml",
    concentration: "EDT",
    family: "Woody Spicy",
    longevity: "6–8 hours",
    occasion: "All day",
    price: 146,
    compareAt: 449,
    notes: {
      top: ["Grapefruit", "Cardamom"],
      heart: ["Sage", "Cinnamon"],
      base: ["Amber", "Musk"],
    },
    description: "Carolina Herrera CH Men EDT For Men 100ML by Carolina Herrera is a woody spicy EDT for men. Opening with grapefruit and cardamom, it settles into sage and cinnamon before a lasting trail of amber and musk.",
  },
  {
    name: "Carolina Herrera CH Men Sport EDT For Men 100ML",
    image: "/perfumes/bottles/carolina-herrera-ch-men-sport-edt-for-men-100ml.jpg",
    brand: "Carolina Herrera",
    category: "men",
    size: "100ml",
    concentration: "EDT",
    family: "Woody Spicy",
    longevity: "6–8 hours",
    occasion: "All day",
    price: 146,
    compareAt: 299,
    notes: {
      top: ["Pineapple", "Mint"],
      heart: ["Sage", "Cinnamon"],
      base: ["Oud", "Leather"],
    },
    description: "Carolina Herrera CH Men Sport EDT For Men 100ML by Carolina Herrera is a woody spicy EDT for men. Opening with pineapple and mint, it settles into sage and cinnamon before a lasting trail of oud and leather.",
  },
  {
    name: "Bentley Momentum EDT for Men 100ML",
    image: "/perfumes/bottles/bentley-momentum-edt-for-men-100ml.jpg",
    brand: "Bentley",
    category: "men",
    size: "100ml",
    concentration: "EDT",
    family: "Woody Spicy",
    longevity: "6–8 hours",
    occasion: "All day",
    price: 119,
    compareAt: 299,
    notes: {
      top: ["Bergamot", "Lemon"],
      heart: ["Cedar", "Nutmeg"],
      base: ["Amber", "Musk"],
    },
    description: "Bentley Momentum EDT for Men 100ML by Bentley is a woody spicy EDT for men. Opening with bergamot and lemon, it settles into cedar and nutmeg before a lasting trail of amber and musk.",
  },
  {
    name: "Calvin Klein One Shock for Her EDT For Women 100ML",
    image: "/perfumes/bottles/calvin-klein-one-shock-for-her-edt-for-women-100ml.jpg",
    brand: "Calvin Klein",
    category: "women",
    size: "100ml",
    concentration: "EDT",
    family: "Floral Oriental",
    longevity: "6–8 hours",
    occasion: "Evening",
    price: 75,
    compareAt: 199,
    notes: {
      top: ["Saffron", "Rose"],
      heart: ["Oud", "Patchouli"],
      base: ["Amber", "Musk"],
    },
    description: "Calvin Klein One Shock for Her EDT For Women 100ML by Calvin Klein is a floral oriental EDT for women. Opening with saffron and rose, it settles into oud and patchouli before a lasting trail of amber and musk.",
  },
  {
    name: "Rasasi Shuhrah Pour Femme EDP For Women 90ML",
    image: "/perfumes/bottles/rasasi-shuhrah-pour-femme-edp-for-women-90ml.jpg",
    brand: "Rasasi",
    category: "women",
    size: "90ml",
    concentration: "EDP",
    family: "Floral Oriental",
    longevity: "8–10 hours",
    occasion: "Evening",
    price: 79,
    compareAt: 129,
    notes: {
      top: ["Saffron", "Rose"],
      heart: ["Oud", "Patchouli"],
      base: ["Amber", "Musk"],
    },
    description: "Rasasi Shuhrah Pour Femme EDP For Women 90ML by Rasasi is a floral oriental EDP for women. Opening with saffron and rose, it settles into oud and patchouli before a lasting trail of amber and musk.",
  },
  {
    name: "Davidoff Cool Water EDT for Women 100ML",
    image: "/perfumes/bottles/davidoff-cool-water-edt-for-women-100ml.jpg",
    brand: "Davidoff",
    category: "women",
    size: "100ml",
    concentration: "EDT",
    family: "Floral Oriental",
    longevity: "6–8 hours",
    occasion: "Evening",
    price: 80,
    compareAt: 149,
    notes: {
      top: ["Saffron", "Rose"],
      heart: ["Oud", "Patchouli"],
      base: ["Amber", "Musk"],
    },
    description: "Davidoff Cool Water EDT for Women 100ML by Davidoff is a floral oriental EDT for women. Opening with saffron and rose, it settles into oud and patchouli before a lasting trail of amber and musk.",
  },
  {
    name: "Versace Red Jeans Eau De Toilette For Women",
    image: "/perfumes/bottles/versace-red-jeans-eau-de-toilette-for-women.jpg",
    brand: "Versace",
    category: "women",
    size: "100ml",
    concentration: "EDT",
    family: "Floral Oriental",
    longevity: "6–8 hours",
    occasion: "Evening",
    price: 89,
    compareAt: 140,
    notes: {
      top: ["Saffron", "Rose"],
      heart: ["Oud", "Patchouli"],
      base: ["Amber", "Musk"],
    },
    description: "Versace Red Jeans Eau De Toilette For Women by Versace is a floral oriental EDT for women. Opening with saffron and rose, it settles into oud and patchouli before a lasting trail of amber and musk.",
  },
  {
    name: "Calvin Klein Obsession EDP for Women 100ML",
    image: "/perfumes/bottles/calvin-klein-obsession-edp-for-women-100ml.jpg",
    brand: "Calvin Klein",
    category: "women",
    size: "100ml",
    concentration: "EDP",
    family: "Floral Oriental",
    longevity: "8–10 hours",
    occasion: "Evening",
    price: 99,
    compareAt: 115,
    notes: {
      top: ["Saffron", "Rose"],
      heart: ["Oud", "Patchouli"],
      base: ["Amber", "Musk"],
    },
    description: "Calvin Klein Obsession EDP for Women 100ML by Calvin Klein is a floral oriental EDP for women. Opening with saffron and rose, it settles into oud and patchouli before a lasting trail of amber and musk.",
  },
  {
    name: "Calvin Klein Escape EDP for Women 100ML",
    image: "/perfumes/bottles/calvin-klein-escape-edp-for-women-100ml.jpg",
    brand: "Calvin Klein",
    category: "women",
    size: "100ml",
    concentration: "EDP",
    family: "Floral Oriental",
    longevity: "8–10 hours",
    occasion: "Evening",
    price: 99,
    compareAt: 199,
    notes: {
      top: ["Saffron", "Rose"],
      heart: ["Oud", "Patchouli"],
      base: ["Amber", "Musk"],
    },
    description: "Calvin Klein Escape EDP for Women 100ML by Calvin Klein is a floral oriental EDP for women. Opening with saffron and rose, it settles into oud and patchouli before a lasting trail of amber and musk.",
  },
  {
    name: "Burberry Brit Burberry Limitted Edition Eau de Parfum For Women",
    image: "/perfumes/bottles/burberry-brit-burberry-limitted-edition-eau-de-parfum-for-women.jpg",
    brand: "Burberry",
    category: "women",
    size: "100ml",
    concentration: "EDP",
    family: "Floral Oriental",
    longevity: "8–10 hours",
    occasion: "Evening",
    price: 109,
    compareAt: 398,
    notes: {
      top: ["Saffron", "Rose"],
      heart: ["Oud", "Patchouli"],
      base: ["Amber", "Musk"],
    },
    description: "Burberry Brit Burberry Limitted Edition Eau de Parfum For Women by Burberry is a floral oriental EDP for women. Opening with saffron and rose, it settles into oud and patchouli before a lasting trail of amber and musk.",
  },
  {
    name: "Davidoff Cool Water Sea Rose Eau De Toilette for Women",
    image: "/perfumes/bottles/davidoff-cool-water-sea-rose-eau-de-toilette-for-women.jpg",
    brand: "Davidoff",
    category: "women",
    size: "100ml",
    concentration: "EDT",
    family: "Floral",
    longevity: "6–8 hours",
    occasion: "All day",
    price: 109,
    compareAt: 129,
    notes: {
      top: ["Mandarin", "Pink Pepper"],
      heart: ["Ylang-Ylang", "Lily"],
      base: ["Sandalwood", "Amber"],
    },
    description: "Davidoff Cool Water Sea Rose Eau De Toilette for Women by Davidoff is a floral EDT for women. Opening with mandarin and pink pepper, it settles into ylang-ylang and lily before a lasting trail of sandalwood and amber.",
  },
  {
    name: "Estee Lauder Sensuous EDP for Women",
    image: "/perfumes/bottles/estee-lauder-sensuous-edp-for-women.jpg",
    brand: "Estee Lauder",
    category: "women",
    size: "100ml",
    concentration: "EDP",
    family: "Floral Oriental",
    longevity: "8–10 hours",
    occasion: "Evening",
    price: 127,
    compareAt: 199,
    notes: {
      top: ["Saffron", "Rose"],
      heart: ["Oud", "Patchouli"],
      base: ["Amber", "Musk"],
    },
    description: "Estee Lauder Sensuous EDP for Women by Estee Lauder is a floral oriental EDP for women. Opening with saffron and rose, it settles into oud and patchouli before a lasting trail of amber and musk.",
  },
  {
    name: "Coach Eau De Parfum for Women",
    image: "/perfumes/bottles/coach-eau-de-parfum-for-women.jpg",
    brand: "Coach",
    category: "women",
    size: "100ml",
    concentration: "EDP",
    family: "Floral Oriental",
    longevity: "8–10 hours",
    occasion: "Evening",
    price: 129,
    compareAt: 179,
    notes: {
      top: ["Saffron", "Rose"],
      heart: ["Oud", "Patchouli"],
      base: ["Amber", "Musk"],
    },
    description: "Coach Eau De Parfum for Women by Coach is a floral oriental EDP for women. Opening with saffron and rose, it settles into oud and patchouli before a lasting trail of amber and musk.",
  },
  {
    name: "Burberry Brit Sheer For Her EDT for Women 100ML",
    image: "/perfumes/bottles/burberry-brit-sheer-for-her-edt-for-women-100ml.jpg",
    brand: "Burberry",
    category: "women",
    size: "100ml",
    concentration: "EDT",
    family: "Floral Oriental",
    longevity: "6–8 hours",
    occasion: "Evening",
    price: 129,
    compareAt: 229,
    notes: {
      top: ["Saffron", "Rose"],
      heart: ["Oud", "Patchouli"],
      base: ["Amber", "Musk"],
    },
    description: "Burberry Brit Sheer For Her EDT for Women 100ML by Burberry is a floral oriental EDT for women. Opening with saffron and rose, it settles into oud and patchouli before a lasting trail of amber and musk.",
  },
  {
    name: "Hugo Boss Woman Eau De Toilette for Women",
    image: "/perfumes/bottles/hugo-boss-woman-eau-de-toilette-for-women.jpg",
    brand: "Hugo Boss",
    category: "women",
    size: "100ml",
    concentration: "EDT",
    family: "Floral Oriental",
    longevity: "6–8 hours",
    occasion: "Evening",
    price: 119,
    compareAt: 199,
    notes: {
      top: ["Saffron", "Rose"],
      heart: ["Oud", "Patchouli"],
      base: ["Amber", "Musk"],
    },
    description: "Hugo Boss Woman Eau De Toilette for Women by Hugo Boss is a floral oriental EDT for women. Opening with saffron and rose, it settles into oud and patchouli before a lasting trail of amber and musk.",
  },
  {
    name: "Burberry London EDP for Women 100ML",
    image: "/perfumes/bottles/burberry-london-edp-for-women-100ml.jpg",
    brand: "Burberry",
    category: "women",
    size: "100ml",
    concentration: "EDP",
    family: "Floral Oriental",
    longevity: "8–10 hours",
    occasion: "Evening",
    price: 139,
    compareAt: 249,
    notes: {
      top: ["Saffron", "Rose"],
      heart: ["Oud", "Patchouli"],
      base: ["Amber", "Musk"],
    },
    description: "Burberry London EDP for Women 100ML by Burberry is a floral oriental EDP for women. Opening with saffron and rose, it settles into oud and patchouli before a lasting trail of amber and musk.",
  },
  {
    name: "Estée Lauder Beautiful EDP for Women 100ML",
    image: "/perfumes/bottles/est-e-lauder-beautiful-edp-for-women-100ml.jpg",
    brand: "Estée Lauder",
    category: "women",
    size: "100ml",
    concentration: "EDP",
    family: "Floral Oriental",
    longevity: "8–10 hours",
    occasion: "Evening",
    price: 140,
    compareAt: 349,
    notes: {
      top: ["Saffron", "Rose"],
      heart: ["Oud", "Patchouli"],
      base: ["Amber", "Musk"],
    },
    description: "Estée Lauder Beautiful EDP for Women 100ML by Estée Lauder is a floral oriental EDP for women. Opening with saffron and rose, it settles into oud and patchouli before a lasting trail of amber and musk.",
  },
  {
    name: "Montblanc Lady Emblem Elixir Eau De Parfum for Women",
    image: "/perfumes/bottles/montblanc-lady-emblem-elixir-eau-de-parfum-for-women.jpg",
    brand: "Montblanc",
    category: "women",
    size: "100ml",
    concentration: "EDP",
    family: "Floral Oriental",
    longevity: "8–10 hours",
    occasion: "Evening",
    price: 159,
    compareAt: 299,
    notes: {
      top: ["Saffron", "Rose"],
      heart: ["Oud", "Patchouli"],
      base: ["Amber", "Musk"],
    },
    description: "Montblanc Lady Emblem Elixir Eau De Parfum for Women by Montblanc is a floral oriental EDP for women. Opening with saffron and rose, it settles into oud and patchouli before a lasting trail of amber and musk.",
  },
  {
    name: "Issey Miyake L`Eau D`Issey EDT for Women 100ML",
    image: "/perfumes/bottles/issey-miyake-l-eau-d-issey-edt-for-women-100ml.jpg",
    brand: "Issey Miyake",
    category: "women",
    size: "100ml",
    concentration: "EDT",
    family: "Floral Oriental",
    longevity: "6–8 hours",
    occasion: "Evening",
    price: 159,
    compareAt: 469,
    notes: {
      top: ["Saffron", "Rose"],
      heart: ["Oud", "Patchouli"],
      base: ["Amber", "Musk"],
    },
    description: "Issey Miyake L`Eau D`Issey EDT for Women 100ML by Issey Miyake is a floral oriental EDT for women. Opening with saffron and rose, it settles into oud and patchouli before a lasting trail of amber and musk.",
  },
  {
    name: "Hugo Boss Deep Red Eau De Parfum for Women",
    image: "/perfumes/bottles/hugo-boss-deep-red-eau-de-parfum-for-women.jpg",
    brand: "Hugo Boss",
    category: "women",
    size: "100ml",
    concentration: "EDP",
    family: "Floral Oriental",
    longevity: "8–10 hours",
    occasion: "Evening",
    price: 159,
    compareAt: 249,
    notes: {
      top: ["Saffron", "Rose"],
      heart: ["Oud", "Patchouli"],
      base: ["Amber", "Musk"],
    },
    description: "Hugo Boss Deep Red Eau De Parfum for Women by Hugo Boss is a floral oriental EDP for women. Opening with saffron and rose, it settles into oud and patchouli before a lasting trail of amber and musk.",
  },
  {
    name: "Montblanc Femme Individuelle Eau De Toilette for Women",
    image: "/perfumes/bottles/montblanc-femme-individuelle-eau-de-toilette-for-women.jpg",
    brand: "Montblanc",
    category: "women",
    size: "100ml",
    concentration: "EDT",
    family: "Floral Oriental",
    longevity: "6–8 hours",
    occasion: "Evening",
    price: 139,
    compareAt: 199,
    notes: {
      top: ["Saffron", "Rose"],
      heart: ["Oud", "Patchouli"],
      base: ["Amber", "Musk"],
    },
    description: "Montblanc Femme Individuelle Eau De Toilette for Women by Montblanc is a floral oriental EDT for women. Opening with saffron and rose, it settles into oud and patchouli before a lasting trail of amber and musk.",
  },
  {
    name: "Coach Floral Blush Eau De Parfum for Women",
    image: "/perfumes/bottles/coach-floral-blush-eau-de-parfum-for-women.jpg",
    brand: "Coach",
    category: "women",
    size: "100ml",
    concentration: "EDP",
    family: "Floral",
    longevity: "8–10 hours",
    occasion: "All day",
    price: 164,
    compareAt: 299,
    notes: {
      top: ["Rose", "Lychee"],
      heart: ["Orange Blossom", "Iris"],
      base: ["Benzoin", "Praline"],
    },
    description: "Coach Floral Blush Eau De Parfum for Women by Coach is a floral EDP for women. Opening with rose and lychee, it settles into orange blossom and iris before a lasting trail of benzoin and praline.",
  },
  {
    name: "Montblanc Signature EDP for Women 90ML",
    image: "/perfumes/bottles/montblanc-signature-edp-for-women-90ml.jpg",
    brand: "Montblanc",
    category: "women",
    size: "90ml",
    concentration: "EDP",
    family: "Floral Oriental",
    longevity: "8–10 hours",
    occasion: "Evening",
    price: 169,
    compareAt: 239,
    notes: {
      top: ["Saffron", "Rose"],
      heart: ["Oud", "Patchouli"],
      base: ["Amber", "Musk"],
    },
    description: "Montblanc Signature EDP for Women 90ML by Montblanc is a floral oriental EDP for women. Opening with saffron and rose, it settles into oud and patchouli before a lasting trail of amber and musk.",
  },
  {
    name: "Dolce & Gabbana L’Imperatrice For Women EDT 100ML",
    image: "/perfumes/bottles/dolce-gabbana-l-imperatrice-for-women-edt-100ml.jpg",
    brand: "Dolce & Gabbana",
    category: "women",
    size: "100ml",
    concentration: "EDT",
    family: "Floral Oriental",
    longevity: "6–8 hours",
    occasion: "Evening",
    price: 189,
    compareAt: 199,
    notes: {
      top: ["Saffron", "Rose"],
      heart: ["Oud", "Patchouli"],
      base: ["Amber", "Musk"],
    },
    description: "Dolce & Gabbana L’Imperatrice For Women EDT 100ML by Dolce & Gabbana is a floral oriental EDT for women. Opening with saffron and rose, it settles into oud and patchouli before a lasting trail of amber and musk.",
  },
  {
    name: "Paco Rabanne Ultraviolet EDP for Women 80ML",
    image: "/perfumes/bottles/paco-rabanne-ultraviolet-edp-for-women-80ml.jpg",
    brand: "Paco Rabanne",
    category: "women",
    size: "80ml",
    concentration: "EDP",
    family: "Floral Oriental",
    longevity: "8–10 hours",
    occasion: "Evening",
    price: 199,
    compareAt: 255,
    notes: {
      top: ["Saffron", "Rose"],
      heart: ["Oud", "Patchouli"],
      base: ["Amber", "Musk"],
    },
    description: "Paco Rabanne Ultraviolet EDP for Women 80ML by Paco Rabanne is a floral oriental EDP for women. Opening with saffron and rose, it settles into oud and patchouli before a lasting trail of amber and musk.",
  },
  {
    name: "Versace Yellow Diamond EDT For Women 90ML",
    image: "/perfumes/bottles/versace-yellow-diamond-edt-for-women-90ml.jpg",
    brand: "Versace",
    category: "women",
    size: "90ml",
    concentration: "EDT",
    family: "Floral Oriental",
    longevity: "6–8 hours",
    occasion: "Evening",
    price: 199,
    compareAt: 299,
    notes: {
      top: ["Saffron", "Rose"],
      heart: ["Oud", "Patchouli"],
      base: ["Amber", "Musk"],
    },
    description: "Versace Yellow Diamond EDT For Women 90ML by Versace is a floral oriental EDT for women. Opening with saffron and rose, it settles into oud and patchouli before a lasting trail of amber and musk.",
  },
  {
    name: "Narciso Rodriguez For Her EDT for Women 100ML",
    image: "/perfumes/bottles/narciso-rodriguez-for-her-edt-for-women-100ml.jpg",
    brand: "Narciso Rodriguez",
    category: "women",
    size: "100ml",
    concentration: "EDT",
    family: "Floral Oriental",
    longevity: "6–8 hours",
    occasion: "Evening",
    price: 207,
    compareAt: 349,
    notes: {
      top: ["Saffron", "Rose"],
      heart: ["Oud", "Patchouli"],
      base: ["Amber", "Musk"],
    },
    description: "Narciso Rodriguez For Her EDT for Women 100ML by Narciso Rodriguez is a floral oriental EDT for women. Opening with saffron and rose, it settles into oud and patchouli before a lasting trail of amber and musk.",
  },
  {
    name: "Versace Pour Femme Dylan Blue EDP for Women 100ML",
    image: "/perfumes/bottles/versace-pour-femme-dylan-blue-edp-for-women-100ml.jpg",
    brand: "Versace",
    category: "women",
    size: "100ml",
    concentration: "EDP",
    family: "Aromatic Fresh",
    longevity: "8–10 hours",
    occasion: "All day",
    price: 207,
    compareAt: 399,
    notes: {
      top: ["Rose", "Lychee"],
      heart: ["Ylang-Ylang", "Lily"],
      base: ["Sandalwood", "Amber"],
    },
    description: "Versace Pour Femme Dylan Blue EDP for Women 100ML by Versace is a aromatic fresh EDP for women. Opening with rose and lychee, it settles into ylang-ylang and lily before a lasting trail of sandalwood and amber.",
  },
  {
    name: "YSL Young Sexy Lovely Eau De Toilette for Women",
    image: "/perfumes/bottles/ysl-young-sexy-lovely-eau-de-toilette-for-women.jpg",
    brand: "YSL",
    category: "women",
    size: "100ml",
    concentration: "EDT",
    family: "Floral Oriental",
    longevity: "6–8 hours",
    occasion: "Evening",
    price: 209,
    compareAt: 299,
    notes: {
      top: ["Saffron", "Rose"],
      heart: ["Oud", "Patchouli"],
      base: ["Amber", "Musk"],
    },
    description: "YSL Young Sexy Lovely Eau De Toilette for Women by YSL is a floral oriental EDT for women. Opening with saffron and rose, it settles into oud and patchouli before a lasting trail of amber and musk.",
  },
  {
    name: "Azzaro Wanted Girl EDP for Women 80ML",
    image: "/perfumes/bottles/azzaro-wanted-girl-edp-for-women-80ml.jpg",
    brand: "Azzaro",
    category: "women",
    size: "80ml",
    concentration: "EDP",
    family: "Floral Oriental",
    longevity: "8–10 hours",
    occasion: "Evening",
    price: 219,
    compareAt: 299,
    notes: {
      top: ["Saffron", "Rose"],
      heart: ["Oud", "Patchouli"],
      base: ["Amber", "Musk"],
    },
    description: "Azzaro Wanted Girl EDP for Women 80ML by Azzaro is a floral oriental EDP for women. Opening with saffron and rose, it settles into oud and patchouli before a lasting trail of amber and musk.",
  },
  {
    name: "Versace Woman Eau De Parfum for Women",
    image: "/perfumes/bottles/versace-woman-eau-de-parfum-for-women.jpg",
    brand: "Versace",
    category: "women",
    size: "100ml",
    concentration: "EDP",
    family: "Floral Oriental",
    longevity: "8–10 hours",
    occasion: "Evening",
    price: 119,
    compareAt: 199,
    notes: {
      top: ["Saffron", "Rose"],
      heart: ["Oud", "Patchouli"],
      base: ["Amber", "Musk"],
    },
    description: "Versace Woman Eau De Parfum for Women by Versace is a floral oriental EDP for women. Opening with saffron and rose, it settles into oud and patchouli before a lasting trail of amber and musk.",
  },
  {
    name: "Montblanc Signature Absolue Eau De Parfum for Women",
    image: "/perfumes/bottles/montblanc-signature-absolue-eau-de-parfum-for-women.jpg",
    brand: "Montblanc",
    category: "women",
    size: "100ml",
    concentration: "EDP",
    family: "Floral Oriental",
    longevity: "8–10 hours",
    occasion: "Evening",
    price: 229,
    compareAt: 299,
    notes: {
      top: ["Saffron", "Rose"],
      heart: ["Oud", "Patchouli"],
      base: ["Amber", "Musk"],
    },
    description: "Montblanc Signature Absolue Eau De Parfum for Women by Montblanc is a floral oriental EDP for women. Opening with saffron and rose, it settles into oud and patchouli before a lasting trail of amber and musk.",
  },
  {
    name: "Estee Lauder Very Estee Eau De Parfum for Women",
    image: "/perfumes/bottles/estee-lauder-very-estee-eau-de-parfum-for-women.jpg",
    brand: "Estee Lauder",
    category: "women",
    size: "100ml",
    concentration: "EDP",
    family: "Floral Oriental",
    longevity: "8–10 hours",
    occasion: "Evening",
    price: 229,
    compareAt: 399,
    notes: {
      top: ["Saffron", "Rose"],
      heart: ["Oud", "Patchouli"],
      base: ["Amber", "Musk"],
    },
    description: "Estee Lauder Very Estee Eau De Parfum for Women by Estee Lauder is a floral oriental EDP for women. Opening with saffron and rose, it settles into oud and patchouli before a lasting trail of amber and musk.",
  },
  {
    name: "Burberry For Women EDP 100ML",
    image: "/perfumes/bottles/burberry-for-women-edp-100ml.jpg",
    brand: "Burberry",
    category: "women",
    size: "100ml",
    concentration: "EDP",
    family: "Floral Oriental",
    longevity: "8–10 hours",
    occasion: "Evening",
    price: 129,
    compareAt: 159,
    notes: {
      top: ["Saffron", "Rose"],
      heart: ["Oud", "Patchouli"],
      base: ["Amber", "Musk"],
    },
    description: "Burberry For Women EDP 100ML by Burberry is a floral oriental EDP for women. Opening with saffron and rose, it settles into oud and patchouli before a lasting trail of amber and musk.",
  },
  {
    name: "Coach Floral EDP for Women 90ML",
    image: "/perfumes/bottles/coach-floral-edp-for-women-90ml.jpg",
    brand: "Coach",
    category: "women",
    size: "90ml",
    concentration: "EDP",
    family: "Floral",
    longevity: "8–10 hours",
    occasion: "All day",
    price: 160,
    compareAt: 299,
    notes: {
      top: ["Bergamot", "Pear"],
      heart: ["Ylang-Ylang", "Lily"],
      base: ["Sandalwood", "Amber"],
    },
    description: "Coach Floral EDP for Women 90ML by Coach is a floral EDP for women. Opening with bergamot and pear, it settles into ylang-ylang and lily before a lasting trail of sandalwood and amber.",
  },
  {
    name: "Chopard Wish Pure Eau De Toilette for Women",
    image: "/perfumes/bottles/chopard-wish-pure-eau-de-toilette-for-women.jpg",
    brand: "Chopard",
    category: "women",
    size: "100ml",
    concentration: "EDT",
    family: "Floral Oriental",
    longevity: "6–8 hours",
    occasion: "Evening",
    price: 139,
    compareAt: 199,
    notes: {
      top: ["Saffron", "Rose"],
      heart: ["Oud", "Patchouli"],
      base: ["Amber", "Musk"],
    },
    description: "Chopard Wish Pure Eau De Toilette for Women by Chopard is a floral oriental EDT for women. Opening with saffron and rose, it settles into oud and patchouli before a lasting trail of amber and musk.",
  },
  {
    name: "Coach Wild Rose Eau De Parfum for Women",
    image: "/perfumes/bottles/coach-wild-rose-eau-de-parfum-for-women.jpg",
    brand: "Coach",
    category: "women",
    size: "100ml",
    concentration: "EDP",
    family: "Floral",
    longevity: "8–10 hours",
    occasion: "All day",
    price: 239,
    compareAt: 399,
    notes: {
      top: ["Peach", "Freesia"],
      heart: ["Orange Blossom", "Iris"],
      base: ["Patchouli", "Cashmere"],
    },
    description: "Coach Wild Rose Eau De Parfum for Women by Coach is a floral EDP for women. Opening with peach and freesia, it settles into orange blossom and iris before a lasting trail of patchouli and cashmere.",
  },
  {
    name: "Elie Saab Girl Of Now Eau De Parfum for Women",
    image: "/perfumes/bottles/elie-saab-girl-of-now-eau-de-parfum-for-women.jpg",
    brand: "Elie Saab",
    category: "women",
    size: "100ml",
    concentration: "EDP",
    family: "Floral Oriental",
    longevity: "8–10 hours",
    occasion: "Evening",
    price: 249,
    compareAt: 499,
    notes: {
      top: ["Saffron", "Rose"],
      heart: ["Oud", "Patchouli"],
      base: ["Amber", "Musk"],
    },
    description: "Elie Saab Girl Of Now Eau De Parfum for Women by Elie Saab is a floral oriental EDP for women. Opening with saffron and rose, it settles into oud and patchouli before a lasting trail of amber and musk.",
  },
  {
    name: "Hugo Boss The Scent EDP for Women 100ML",
    image: "/perfumes/bottles/hugo-boss-the-scent-edp-for-women-100ml.jpg",
    brand: "Hugo Boss",
    category: "women",
    size: "100ml",
    concentration: "EDP",
    family: "Floral Oriental",
    longevity: "8–10 hours",
    occasion: "Evening",
    price: 249,
    compareAt: 399,
    notes: {
      top: ["Saffron", "Rose"],
      heart: ["Oud", "Patchouli"],
      base: ["Amber", "Musk"],
    },
    description: "Hugo Boss The Scent EDP for Women 100ML by Hugo Boss is a floral oriental EDP for women. Opening with saffron and rose, it settles into oud and patchouli before a lasting trail of amber and musk.",
  },
  {
    name: "Hugo Boss XX Eau De Toilette For Women",
    image: "/perfumes/bottles/hugo-boss-xx-eau-de-toilette-for-women.jpg",
    brand: "Hugo Boss",
    category: "women",
    size: "100ml",
    concentration: "EDT",
    family: "Floral Oriental",
    longevity: "6–8 hours",
    occasion: "Evening",
    price: 179,
    compareAt: 239,
    notes: {
      top: ["Saffron", "Rose"],
      heart: ["Oud", "Patchouli"],
      base: ["Amber", "Musk"],
    },
    description: "Hugo Boss XX Eau De Toilette For Women by Hugo Boss is a floral oriental EDT for women. Opening with saffron and rose, it settles into oud and patchouli before a lasting trail of amber and musk.",
  },
  {
    name: "Carolina Herrera Chic EDP for Women 80ML",
    image: "/perfumes/bottles/carolina-herrera-chic-edp-for-women-80ml.jpg",
    brand: "Carolina Herrera",
    category: "women",
    size: "80ml",
    concentration: "EDP",
    family: "Floral Oriental",
    longevity: "8–10 hours",
    occasion: "Evening",
    price: 239,
    compareAt: 399,
    notes: {
      top: ["Saffron", "Rose"],
      heart: ["Oud", "Patchouli"],
      base: ["Amber", "Musk"],
    },
    description: "Carolina Herrera Chic EDP for Women 80ML by Carolina Herrera is a floral oriental EDP for women. Opening with saffron and rose, it settles into oud and patchouli before a lasting trail of amber and musk.",
  },
  {
    name: "Calvin Klein Eternity Moment EDP for Women 100ML",
    image: "/perfumes/bottles/calvin-klein-eternity-moment-edp-for-women-100ml.jpg",
    brand: "Calvin Klein",
    category: "women",
    size: "100ml",
    concentration: "EDP",
    family: "Floral Oriental",
    longevity: "8–10 hours",
    occasion: "Evening",
    price: 99,
    compareAt: 199,
    notes: {
      top: ["Saffron", "Rose"],
      heart: ["Oud", "Patchouli"],
      base: ["Amber", "Musk"],
    },
    description: "Calvin Klein Eternity Moment EDP for Women 100ML by Calvin Klein is a floral oriental EDP for women. Opening with saffron and rose, it settles into oud and patchouli before a lasting trail of amber and musk.",
  },
  {
    name: "Gucci Bamboo Eau De Parfum for Women",
    image: "/perfumes/bottles/gucci-bamboo-eau-de-parfum-for-women.jpg",
    brand: "Gucci",
    category: "women",
    size: "100ml",
    concentration: "EDP",
    family: "Floral Oriental",
    longevity: "8–10 hours",
    occasion: "Evening",
    price: 226,
    compareAt: 459,
    notes: {
      top: ["Saffron", "Rose"],
      heart: ["Oud", "Patchouli"],
      base: ["Amber", "Musk"],
    },
    description: "Gucci Bamboo Eau De Parfum for Women by Gucci is a floral oriental EDP for women. Opening with saffron and rose, it settles into oud and patchouli before a lasting trail of amber and musk.",
  },
  {
    name: "Elie Saab Girl Of Now Shine Eau De Parfum for Women",
    image: "/perfumes/bottles/elie-saab-girl-of-now-shine-eau-de-parfum-for-women.jpg",
    brand: "Elie Saab",
    category: "women",
    size: "100ml",
    concentration: "EDP",
    family: "Floral Oriental",
    longevity: "8–10 hours",
    occasion: "Evening",
    price: 259,
    compareAt: 460,
    notes: {
      top: ["Saffron", "Rose"],
      heart: ["Oud", "Patchouli"],
      base: ["Amber", "Musk"],
    },
    description: "Elie Saab Girl Of Now Shine Eau De Parfum for Women by Elie Saab is a floral oriental EDP for women. Opening with saffron and rose, it settles into oud and patchouli before a lasting trail of amber and musk.",
  },
  {
    name: "YSL Saharienne Eau De Toilette for Women",
    image: "/perfumes/bottles/ysl-saharienne-eau-de-toilette-for-women.jpg",
    brand: "YSL",
    category: "women",
    size: "100ml",
    concentration: "EDT",
    family: "Floral Oriental",
    longevity: "6–8 hours",
    occasion: "Evening",
    price: 249,
    compareAt: 399,
    notes: {
      top: ["Saffron", "Rose"],
      heart: ["Oud", "Patchouli"],
      base: ["Amber", "Musk"],
    },
    description: "YSL Saharienne Eau De Toilette for Women by YSL is a floral oriental EDT for women. Opening with saffron and rose, it settles into oud and patchouli before a lasting trail of amber and musk.",
  },
  {
    name: "Calvin Klein One EDT for Unisex 100ML",
    image: "/perfumes/bottles/calvin-klein-one-edt-for-unisex-100ml.jpg",
    brand: "Calvin Klein",
    category: "unisex",
    size: "100ml",
    concentration: "EDT",
    family: "Woody Floral",
    longevity: "6–8 hours",
    occasion: "All day",
    price: 88,
    compareAt: 189,
    notes: {
      top: ["Bergamot", "Cardamom"],
      heart: ["Lavender", "Orris"],
      base: ["Musk", "Amber"],
    },
    description: "Calvin Klein One EDT for Unisex 100ML by Calvin Klein is a woody floral EDT for everyone. Opening with bergamot and cardamom, it settles into lavender and orris before a lasting trail of musk and amber.",
  },
  {
    name: "Ahmed Al Maghribi Kaaf Eau De Parfum for Unisex",
    image: "/perfumes/bottles/ahmed-al-maghribi-kaaf-eau-de-parfum-for-unisex.jpg",
    brand: "Ahmed Al Maghribi",
    category: "unisex",
    size: "100ml",
    concentration: "EDP",
    family: "Woody Floral",
    longevity: "8–10 hours",
    occasion: "All day",
    price: 129,
    compareAt: 199,
    notes: {
      top: ["Fig Leaf", "Pepper"],
      heart: ["Iris", "Incense"],
      base: ["Musk", "Amber"],
    },
    description: "Ahmed Al Maghribi Kaaf Eau De Parfum for Unisex by Ahmed Al Maghribi is a woody floral EDP for everyone. Opening with fig leaf and pepper, it settles into iris and incense before a lasting trail of musk and amber.",
  },
  {
    name: "Chopard Rose Malaki EDP for Unisex 80ML",
    image: "/perfumes/bottles/chopard-rose-malaki-edp-for-unisex-80ml.jpg",
    brand: "Chopard",
    category: "unisex",
    size: "80ml",
    concentration: "EDP",
    family: "Woody Oriental",
    longevity: "8–10 hours",
    occasion: "Evening",
    price: 209,
    compareAt: 299,
    notes: {
      top: ["Saffron", "Rose"],
      heart: ["Oud", "Patchouli"],
      base: ["Amber", "Musk"],
    },
    description: "Chopard Rose Malaki EDP for Unisex 80ML by Chopard is a woody oriental EDP for everyone. Opening with saffron and rose, it settles into oud and patchouli before a lasting trail of amber and musk.",
  },
  {
    name: "Calvin Klein One Reflections EDT for Unisex 100ML",
    image: "/perfumes/bottles/calvin-klein-one-reflections-edt-for-unisex-100ml.jpg",
    brand: "Calvin Klein",
    category: "unisex",
    size: "100ml",
    concentration: "EDT",
    family: "Woody Floral",
    longevity: "6–8 hours",
    occasion: "All day",
    price: 80,
    compareAt: 249,
    notes: {
      top: ["Bergamot", "Cardamom"],
      heart: ["Lavender", "Orris"],
      base: ["Leather", "Patchouli"],
    },
    description: "Calvin Klein One Reflections EDT for Unisex 100ML by Calvin Klein is a woody floral EDT for everyone. Opening with bergamot and cardamom, it settles into lavender and orris before a lasting trail of leather and patchouli.",
  },
  {
    name: "Mancera French Riviera EDP for Unisex 120ML",
    image: "/perfumes/bottles/mancera-french-riviera-edp-for-unisex-120ml.jpg",
    brand: "Mancera",
    category: "unisex",
    size: "120ml",
    concentration: "EDP",
    family: "Woody Floral",
    longevity: "8–10 hours",
    occasion: "All day",
    price: 329,
    compareAt: 499,
    notes: {
      top: ["Saffron", "Citrus"],
      heart: ["Rose", "Cedar"],
      base: ["Leather", "Patchouli"],
    },
    description: "Mancera French Riviera EDP for Unisex 120ML by Mancera is a woody floral EDP for everyone. Opening with saffron and citrus, it settles into rose and cedar before a lasting trail of leather and patchouli.",
  },
  {
    name: "Calvin Klein Be EDT for Unisex 100ML",
    image: "/perfumes/bottles/calvin-klein-be-edt-for-unisex-100ml.jpg",
    brand: "Calvin Klein",
    category: "unisex",
    size: "100ml",
    concentration: "EDT",
    family: "Woody Floral",
    longevity: "6–8 hours",
    occasion: "All day",
    price: 73,
    compareAt: 199,
    notes: {
      top: ["Bergamot", "Cardamom"],
      heart: ["Rose", "Cedar"],
      base: ["Musk", "Amber"],
    },
    description: "Calvin Klein Be EDT for Unisex 100ML by Calvin Klein is a woody floral EDT for everyone. Opening with bergamot and cardamom, it settles into rose and cedar before a lasting trail of musk and amber.",
  },
  {
    name: "Ahmed Al Maghribi Summer Oud Eau De Parfum for Unisex",
    image: "/perfumes/bottles/ahmed-al-maghribi-summer-oud-eau-de-parfum-for-unisex.jpg",
    brand: "Ahmed Al Maghribi",
    category: "unisex",
    size: "100ml",
    concentration: "EDP",
    family: "Woody Oriental",
    longevity: "8–10 hours",
    occasion: "Evening",
    price: 160,
    compareAt: 299,
    notes: {
      top: ["Saffron", "Rose"],
      heart: ["Oud", "Patchouli"],
      base: ["Amber", "Musk"],
    },
    description: "Ahmed Al Maghribi Summer Oud Eau De Parfum for Unisex by Ahmed Al Maghribi is a woody oriental EDP for everyone. Opening with saffron and rose, it settles into oud and patchouli before a lasting trail of amber and musk.",
  },
  {
    name: "Chopard Musk Malaki Eau De Parfum for Unisex",
    image: "/perfumes/bottles/chopard-musk-malaki-eau-de-parfum-for-unisex.jpg",
    brand: "Chopard",
    category: "unisex",
    size: "100ml",
    concentration: "EDP",
    family: "Woody Oriental",
    longevity: "8–10 hours",
    occasion: "Evening",
    price: 199,
    compareAt: 299,
    notes: {
      top: ["Saffron", "Rose"],
      heart: ["Oud", "Patchouli"],
      base: ["Amber", "Musk"],
    },
    description: "Chopard Musk Malaki Eau De Parfum for Unisex by Chopard is a woody oriental EDP for everyone. Opening with saffron and rose, it settles into oud and patchouli before a lasting trail of amber and musk.",
  },
  {
    name: "BYREDO 1996 Inez & Vinoodh Unisex EDP 100ML",
    image: "/perfumes/bottles/byredo-1996-inez-vinoodh-unisex-edp-100ml.jpg",
    brand: "Byredo",
    category: "unisex",
    size: "100ml",
    concentration: "EDP",
    family: "Woody Floral",
    longevity: "8–10 hours",
    occasion: "All day",
    price: 429,
    compareAt: 599,
    notes: {
      top: ["Bergamot", "Cardamom"],
      heart: ["Iris", "Incense"],
      base: ["Sandalwood", "Vetiver"],
    },
    description: "BYREDO 1996 Inez & Vinoodh Unisex EDP 100ML by Byredo is a woody floral EDP for everyone. Opening with bergamot and cardamom, it settles into iris and incense before a lasting trail of sandalwood and vetiver.",
  },
  {
    name: "Maison Margiela Replica On A Date EDT Unisex 100ML",
    image: "/perfumes/bottles/maison-margiela-replica-on-a-date-edt-unisex-100ml.jpg",
    brand: "Maison Margiela",
    category: "unisex",
    size: "100ml",
    concentration: "EDT",
    family: "Woody Floral",
    longevity: "6–8 hours",
    occasion: "All day",
    price: 339,
    compareAt: 599,
    notes: {
      top: ["Saffron", "Citrus"],
      heart: ["Rose", "Cedar"],
      base: ["Leather", "Patchouli"],
    },
    description: "Maison Margiela Replica On A Date EDT Unisex 100ML by Maison Margiela is a woody floral EDT for everyone. Opening with saffron and citrus, it settles into rose and cedar before a lasting trail of leather and patchouli.",
  },
  {
    name: "Carolina Herrera Rose Cruise EDT for Unisex 100ML",
    image: "/perfumes/bottles/carolina-herrera-rose-cruise-edt-for-unisex-100ml.jpg",
    brand: "Carolina Herrera",
    category: "unisex",
    size: "100ml",
    concentration: "EDT",
    family: "Floral",
    longevity: "6–8 hours",
    occasion: "All day",
    price: 469,
    compareAt: 599,
    notes: {
      top: ["Fig Leaf", "Pepper"],
      heart: ["Rose", "Cedar"],
      base: ["Musk", "Amber"],
    },
    description: "Carolina Herrera Rose Cruise EDT for Unisex 100ML by Carolina Herrera is a floral EDT for everyone. Opening with fig leaf and pepper, it settles into rose and cedar before a lasting trail of musk and amber.",
  },
  {
    name: "Maison Margiela Replica Under The Stars For EDT Unisex 100ML",
    image: "/perfumes/bottles/maison-margiela-replica-under-the-stars-for-edt-unisex-100ml.jpg",
    brand: "Maison Margiela",
    category: "unisex",
    size: "100ml",
    concentration: "EDT",
    family: "Woody Floral",
    longevity: "6–8 hours",
    occasion: "All day",
    price: 349,
    compareAt: 599,
    notes: {
      top: ["Bergamot", "Cardamom"],
      heart: ["Rose", "Cedar"],
      base: ["Leather", "Patchouli"],
    },
    description: "Maison Margiela Replica Under The Stars For EDT Unisex 100ML by Maison Margiela is a woody floral EDT for everyone. Opening with bergamot and cardamom, it settles into rose and cedar before a lasting trail of leather and patchouli.",
  },
  {
    name: "Jo Malone Bronze Wood & Leather Cologne Intense For unisex 100ML",
    image: "/perfumes/bottles/jo-malone-bronze-wood-leather-cologne-intense-for-unisex-100ml.jpg",
    brand: "Jo Malone",
    category: "unisex",
    size: "100ml",
    concentration: "EDP",
    family: "Leather",
    longevity: "8–10 hours",
    occasion: "Evening",
    price: 499,
    compareAt: 699,
    notes: {
      top: ["Cardamom"],
      heart: ["Leather", "Jasmine"],
      base: ["Patchouli", "Amber"],
    },
    description: "Jo Malone Bronze Wood & Leather Cologne Intense For unisex 100ML by Jo Malone is a leather EDP for everyone. Opening with cardamom, it settles into leather and jasmine before a lasting trail of patchouli and amber.",
  },
  {
    name: "Gucci Intense Oud Eau De Parfum for Unisex",
    image: "/perfumes/bottles/gucci-intense-oud-eau-de-parfum-for-unisex.jpg",
    brand: "Gucci",
    category: "unisex",
    size: "100ml",
    concentration: "EDP",
    family: "Woody Oriental",
    longevity: "8–10 hours",
    occasion: "Evening",
    price: 499,
    compareAt: 650,
    notes: {
      top: ["Saffron", "Rose"],
      heart: ["Oud", "Patchouli"],
      base: ["Amber", "Musk"],
    },
    description: "Gucci Intense Oud Eau De Parfum for Unisex by Gucci is a woody oriental EDP for everyone. Opening with saffron and rose, it settles into oud and patchouli before a lasting trail of amber and musk.",
  },
  {
    name: "Mancera Cedrat Boise Eau De Parfum for Unisex",
    image: "/perfumes/bottles/mancera-cedrat-boise-eau-de-parfum-for-unisex.jpg",
    brand: "Mancera",
    category: "unisex",
    size: "100ml",
    concentration: "EDP",
    family: "Woody Floral",
    longevity: "8–10 hours",
    occasion: "All day",
    price: 319,
    compareAt: 499,
    notes: {
      top: ["Bergamot", "Cardamom"],
      heart: ["Iris", "Incense"],
      base: ["Sandalwood", "Vetiver"],
    },
    description: "Mancera Cedrat Boise Eau De Parfum for Unisex by Mancera is a woody floral EDP for everyone. Opening with bergamot and cardamom, it settles into iris and incense before a lasting trail of sandalwood and vetiver.",
  },
  {
    name: "Narciso Rodriguez Oud Musc Eau De Parfum Intense for Unisex",
    image: "/perfumes/bottles/narciso-rodriguez-oud-musc-eau-de-parfum-intense-for-unisex.jpg",
    brand: "Narciso Rodriguez",
    category: "unisex",
    size: "100ml",
    concentration: "EDP",
    family: "Woody Oriental",
    longevity: "8–10 hours",
    occasion: "Evening",
    price: 459,
    compareAt: 699,
    notes: {
      top: ["Saffron", "Rose"],
      heart: ["Oud", "Patchouli"],
      base: ["Amber", "Musk"],
    },
    description: "Narciso Rodriguez Oud Musc Eau De Parfum Intense for Unisex by Narciso Rodriguez is a woody oriental EDP for everyone. Opening with saffron and rose, it settles into oud and patchouli before a lasting trail of amber and musk.",
  },
  {
    name: "Guerlain Absolus Allegoria Oud Essentiel Eau De Parfum for Unisex",
    image: "/perfumes/bottles/guerlain-absolus-allegoria-oud-essentiel-eau-de-parfum-for-unisex.jpg",
    brand: "Guerlain",
    category: "unisex",
    size: "100ml",
    concentration: "EDP",
    family: "Woody Oriental",
    longevity: "8–10 hours",
    occasion: "Evening",
    price: 599,
    compareAt: 849,
    notes: {
      top: ["Saffron", "Rose"],
      heart: ["Oud", "Patchouli"],
      base: ["Amber", "Musk"],
    },
    description: "Guerlain Absolus Allegoria Oud Essentiel Eau De Parfum for Unisex by Guerlain is a woody oriental EDP for everyone. Opening with saffron and rose, it settles into oud and patchouli before a lasting trail of amber and musk.",
  },
  {
    name: "Jo Malone English Oak & Hazelnut Cologne For Unisex Parfum",
    image: "/perfumes/bottles/jo-malone-english-oak-hazelnut-cologne-for-unisex-parfum.jpg",
    brand: "Jo Malone",
    category: "unisex",
    size: "100ml",
    concentration: "Parfum",
    family: "Woody Floral",
    longevity: "8–10 hours",
    occasion: "All day",
    price: 562,
    compareAt: 635,
    notes: {
      top: ["Saffron", "Citrus"],
      heart: ["Jasmine", "Oud"],
      base: ["Musk", "Amber"],
    },
    description: "Jo Malone English Oak & Hazelnut Cologne For Unisex Parfum by Jo Malone is a woody floral Parfum for everyone. Opening with saffron and citrus, it settles into jasmine and oud before a lasting trail of musk and amber.",
  },
  {
    name: "Tom Ford Bois Pacifique Eau de Parfum 100ml For Unisex",
    image: "/perfumes/bottles/tom-ford-bois-pacifique-eau-de-parfum-100ml-for-unisex.jpg",
    brand: "Tom Ford",
    category: "unisex",
    size: "100ml",
    concentration: "EDP",
    family: "Woody Floral",
    longevity: "8–10 hours",
    occasion: "All day",
    price: 629,
    compareAt: 899,
    notes: {
      top: ["Saffron", "Citrus"],
      heart: ["Iris", "Incense"],
      base: ["Sandalwood", "Vetiver"],
    },
    description: "Tom Ford Bois Pacifique Eau de Parfum 100ml For Unisex by Tom Ford is a woody floral EDP for everyone. Opening with saffron and citrus, it settles into iris and incense before a lasting trail of sandalwood and vetiver.",
  },
  {
    name: "Mancera Red Tobacco EDP for Unisex 120ML",
    image: "/perfumes/bottles/mancera-red-tobacco-edp-for-unisex-120ml.jpg",
    brand: "Mancera",
    category: "unisex",
    size: "120ml",
    concentration: "EDP",
    family: "Leather",
    longevity: "8–10 hours",
    occasion: "Evening",
    price: 339,
    compareAt: 449,
    notes: {
      top: ["Cardamom"],
      heart: ["Leather", "Jasmine"],
      base: ["Patchouli", "Amber"],
    },
    description: "Mancera Red Tobacco EDP for Unisex 120ML by Mancera is a leather EDP for everyone. Opening with cardamom, it settles into leather and jasmine before a lasting trail of patchouli and amber.",
  },
  {
    name: "Maison Margiela Replica Dancing On The Moon EDP For Unisex 100ML",
    image: "/perfumes/bottles/maison-margiela-replica-dancing-on-the-moon-edp-for-unisex-100ml.jpg",
    brand: "Maison Margiela",
    category: "unisex",
    size: "100ml",
    concentration: "EDP",
    family: "Woody Floral",
    longevity: "8–10 hours",
    occasion: "All day",
    price: 449,
    compareAt: 699,
    notes: {
      top: ["Saffron", "Citrus"],
      heart: ["Jasmine", "Oud"],
      base: ["Leather", "Patchouli"],
    },
    description: "Maison Margiela Replica Dancing On The Moon EDP For Unisex 100ML by Maison Margiela is a woody floral EDP for everyone. Opening with saffron and citrus, it settles into jasmine and oud before a lasting trail of leather and patchouli.",
  },
  {
    name: "HermES Terre d'Hermes Voyage d'Hermes Parfum for Unisex 100ML",
    image: "/perfumes/bottles/hermes-terre-d-hermes-voyage-d-hermes-parfum-for-unisex-100ml.jpg",
    brand: "Hermes",
    category: "unisex",
    size: "100ml",
    concentration: "Parfum",
    family: "Woody Floral",
    longevity: "8–10 hours",
    occasion: "All day",
    price: 389,
    compareAt: 649,
    notes: {
      top: ["Pink Pepper", "Tea"],
      heart: ["Jasmine", "Oud"],
      base: ["Sandalwood", "Vetiver"],
    },
    description: "HermES Terre d'Hermes Voyage d'Hermes Parfum for Unisex 100ML by Hermes is a woody floral Parfum for everyone. Opening with pink pepper and tea, it settles into jasmine and oud before a lasting trail of sandalwood and vetiver.",
  },
  {
    name: "Carolina Herrera Vetiver Paradise EDT for Unisex 100ML",
    image: "/perfumes/bottles/carolina-herrera-vetiver-paradise-edt-for-unisex-100ml.jpg",
    brand: "Carolina Herrera",
    category: "unisex",
    size: "100ml",
    concentration: "EDT",
    family: "Woody Floral",
    longevity: "6–8 hours",
    occasion: "All day",
    price: 549,
    compareAt: 749,
    notes: {
      top: ["Saffron", "Citrus"],
      heart: ["Rose", "Cedar"],
      base: ["Sandalwood", "Vetiver"],
    },
    description: "Carolina Herrera Vetiver Paradise EDT for Unisex 100ML by Carolina Herrera is a woody floral EDT for everyone. Opening with saffron and citrus, it settles into rose and cedar before a lasting trail of sandalwood and vetiver.",
  },
  {
    name: "Jo Malone Red Hibiscus For Unisex Cologne Intense 100ML",
    image: "/perfumes/bottles/jo-malone-red-hibiscus-for-unisex-cologne-intense-100ml.jpg",
    brand: "Jo Malone",
    category: "unisex",
    size: "100ml",
    concentration: "EDP",
    family: "Woody Floral",
    longevity: "8–10 hours",
    occasion: "All day",
    price: 649,
    compareAt: 899,
    notes: {
      top: ["Bergamot", "Cardamom"],
      heart: ["Iris", "Incense"],
      base: ["Musk", "Amber"],
    },
    description: "Jo Malone Red Hibiscus For Unisex Cologne Intense 100ML by Jo Malone is a woody floral EDP for everyone. Opening with bergamot and cardamom, it settles into iris and incense before a lasting trail of musk and amber.",
  },
  {
    name: "Ahmed Al Maghribi Azure Royal For Unisex Extrait De Parfum 100ml",
    image: "/perfumes/bottles/ahmed-al-maghribi-azure-royal-for-unisex-extrait-de-parfum-100ml.jpg",
    brand: "Ahmed Al Maghribi",
    category: "unisex",
    size: "100ml",
    concentration: "Extrait",
    family: "Woody Floral",
    longevity: "8–10 hours",
    occasion: "All day",
    price: 75,
    compareAt: 100,
    notes: {
      top: ["Bergamot", "Cardamom"],
      heart: ["Lavender", "Orris"],
      base: ["Musk", "Amber"],
    },
    description: "Ahmed Al Maghribi Azure Royal For Unisex Extrait De Parfum 100ml by Ahmed Al Maghribi is a woody floral Extrait for everyone. Opening with bergamot and cardamom, it settles into lavender and orris before a lasting trail of musk and amber.",
  },
  {
    name: "Lattafa Badee Al Oud For Glory For Unisex Eau de Parfum 100ML",
    image: "/perfumes/bottles/lattafa-badee-al-oud-for-glory-for-unisex-eau-de-parfum-100ml.jpg",
    brand: "Lattafa",
    category: "unisex",
    size: "100ml",
    concentration: "EDP",
    family: "Woody Oriental",
    longevity: "8–10 hours",
    occasion: "Evening",
    price: 75,
    compareAt: 99,
    notes: {
      top: ["Saffron", "Rose"],
      heart: ["Oud", "Patchouli"],
      base: ["Amber", "Musk"],
    },
    description: "Lattafa Badee Al Oud For Glory For Unisex Eau de Parfum 100ML by Lattafa is a woody oriental EDP for everyone. Opening with saffron and rose, it settles into oud and patchouli before a lasting trail of amber and musk.",
  },
  {
    name: "Maison Alhambra Jean Lowe Immortal Unisex Eau De Parfum 100ml",
    image: "/perfumes/bottles/maison-alhambra-jean-lowe-immortal-unisex-eau-de-parfum-100ml.jpg",
    brand: "Maison Alhambra",
    category: "unisex",
    size: "100ml",
    concentration: "EDP",
    family: "Woody Floral",
    longevity: "8–10 hours",
    occasion: "All day",
    price: 79,
    compareAt: 125,
    notes: {
      top: ["Saffron", "Citrus"],
      heart: ["Lavender", "Orris"],
      base: ["Vanilla", "Tonka"],
    },
    description: "Maison Alhambra Jean Lowe Immortal Unisex Eau De Parfum 100ml by Maison Alhambra is a woody floral EDP for everyone. Opening with saffron and citrus, it settles into lavender and orris before a lasting trail of vanilla and tonka.",
  },
  {
    name: "Maison Alhambra Pink Velvet For Unisex Eau De Parfum 80ml",
    image: "/perfumes/bottles/maison-alhambra-pink-velvet-for-unisex-eau-de-parfum-80ml.jpg",
    brand: "Maison Alhambra",
    category: "unisex",
    size: "80ml",
    concentration: "EDP",
    family: "Woody Floral",
    longevity: "8–10 hours",
    occasion: "All day",
    price: 75,
    compareAt: 125,
    notes: {
      top: ["Saffron", "Citrus"],
      heart: ["Rose", "Cedar"],
      base: ["Sandalwood", "Vetiver"],
    },
    description: "Maison Alhambra Pink Velvet For Unisex Eau De Parfum 80ml by Maison Alhambra is a woody floral EDP for everyone. Opening with saffron and citrus, it settles into rose and cedar before a lasting trail of sandalwood and vetiver.",
  },
  {
    name: "Al Haramain Detour Noir For Unisex Eau De Parfume 100ML",
    image: "/perfumes/bottles/al-haramain-detour-noir-for-unisex-eau-de-parfume-100ml.jpg",
    brand: "Al Haramain",
    category: "unisex",
    size: "100ml",
    concentration: "EDP",
    family: "Woody Floral",
    longevity: "8–10 hours",
    occasion: "All day",
    price: 85,
    compareAt: 125,
    notes: {
      top: ["Bergamot", "Cardamom"],
      heart: ["Lavender", "Orris"],
      base: ["Sandalwood", "Vetiver"],
    },
    description: "Al Haramain Detour Noir For Unisex Eau De Parfume 100ML by Al Haramain is a woody floral EDP for everyone. Opening with bergamot and cardamom, it settles into lavender and orris before a lasting trail of sandalwood and vetiver.",
  },
  {
    name: "Lattafa Bade'E Al Oud Amethyst For Unisex Eau De Parfum 100ML",
    image: "/perfumes/bottles/lattafa-bade-e-al-oud-amethyst-for-unisex-eau-de-parfum-100ml.jpg",
    brand: "Lattafa",
    category: "unisex",
    size: "100ml",
    concentration: "EDP",
    family: "Woody Oriental",
    longevity: "8–10 hours",
    occasion: "Evening",
    price: 79,
    compareAt: 99,
    notes: {
      top: ["Saffron", "Rose"],
      heart: ["Oud", "Patchouli"],
      base: ["Amber", "Musk"],
    },
    description: "Lattafa Bade'E Al Oud Amethyst For Unisex Eau De Parfum 100ML by Lattafa is a woody oriental EDP for everyone. Opening with saffron and rose, it settles into oud and patchouli before a lasting trail of amber and musk.",
  },
]
